// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'CORTIFEN 200.25®', imageSrc: 'img/anestesicos/cortifen.png', descripProdu: 'Indicaciones: Para el tratamiento de las afecciones del aparato locomotor de tipo primario y coadyuvante a la antibioterapia en el tratamiento de artritis infecciones. Apropiado en los procesos inflamatorios comunes a osteopatías, adenopatías, neuropatías, mastitis, combatiendo en todos ellos el proceso congestivo y los síntomas dolorosos que los acompañan.' },
    { name: 'TOLFÉN L.A. 8%® | TOLFEMAX A.P. 8%', imageSrc: 'img/anestesicos/tolfe.png', descripProdu: 'Indicaciones: Para el tratamiento de mastitis bovina aguda (el ácido tolfenámico es el único AINE aprobado para tratar las mastitis con una sola inyección), enfermedades respiratorias bacterianas agudas, síndrome mastitis-metritis-agalactia, siempre asociado a una terapia antibiótica. Además, es efectivo en cualquier patología que curse con fiebre, inflamación y/o dolor (terapia antiinflamatoria, antitóxica, analgésica y/o antipirética).' },
    { name: 'DIBROSAL', imageSrc: 'img/anestesicos/DIBROSAL.jpg', descripProdu: 'Indicaciones: Está indicado para el tratamiento de afecciones respiratoria que cursan con producción de moco con alta densidad y fiebre, fluidifica y favorece la expulsión del moco y controla la fiebre.' },
    { name: 'OVERXICAM', imageSrc: 'img/anestesicos/overxicam.png', descripProdu: 'Indicaciones: Bovinos: Tratamiento de infecciones respiratorias agudas, diarreas, mastitis, edema de ubre e inflamaciones podales. Porcinos: Trastornos no infecciosos del aparato locomotor, síntomas de cojeras e inflamación, septicemia, toxemia puer-peral. Equinos: Trastornos musculoesqueléticos agudos y crónicos.' },
    { name: 'DICOGÁN®', imageSrc: 'img/anestesicos/dicogan.jpg', descripProdu: 'Indicaciones: Solución inyectable con efecto antiinflamatorio, analgésico, antipirético indicado en bovinos, equinos, porcinos, ovinos y caprinos en casos agudos por traumatismo músculo esquelético, como artritis, osteoartritis, bursitis, tendinitis, tendosinovitis. En tratamiento de procesos de dolor visceral y fiebre como cólico y traumatismo de órganos internos. Tratamiento de dolor postquirúrgico.' },
    { name: 'KENOGÁN®', imageSrc: 'img/anestesicos/kenogan.jpg', descripProdu: 'Indicaciones: Solución inyectable con efecto antiinflamatorio, analgésico, antipirético en alteraciones no infecciosas de los sistemas osteoarticular y músculo esquelético. En bovinos y porcinos como coadyuvante en el tratamiento de mastitis bacteriana aguda, junto con la terapia antibiótica necesaria. En porcinos como antipirético. En equinos para aliviar el dolor visceral asociado con cólico. En caninos y gatos para aliviar el dolor y la inflamación en procesos posquirúrgicos o traumáticos.' },
    { name: 'DEXAMETASONA FM®', imageSrc: 'img/anestesicos/dexametasona.png', descripProdu: 'Indicaciones: Antinflamatorio, Analgésico, Antirreumático. Indicado en alergias, artritis, hipoglicemias, inflamaciones, traumatismo y estrés en Bovinos, Equinos, Porcinos, Ovinos, Caprinos y pequeños animales.' },
    { name: 'DIPIRONA 50%®', imageSrc: 'img/anestesicos/dipirona.png', descripProdu: 'Indicaciones: Antiinflamatorio no esteroideo, con acción analgésica, antipirética, antiespasmódica y antiinflamatoria. Indicado para el tratamiento y la prevención de todos aquellos procesos agudos y crónicos que cursen con inflamación, dolor, fiebre, espasmos, cólicos, procesos osteoarticulares y musculoesqueleticos como artritis, artrosis, osteoartritis, etc, enfermedad articular degenerativa síndorme ciático, para la prevención de inflamaciones postoperatorias, shock endotóxico.' },
    { name: 'FURODEX®', imageSrc: 'img/anestesicos/furodex.png', descripProdu: 'Indicaciones: Edemas de ubre y estructuras anexas, edema o inflamación de prepucio, ascitis, hidrotórax. Edemas generalizados (anasarca), pulmonares y bronquiales de origen parasitario o traumático.' },
    { name: 'FYNACOL®', imageSrc: 'img/anestesicos/fynacol.png', descripProdu: 'Indicaciones: En procesos inflamatorios y doloroso tales como neumonías, artritis, tendinitis, espondilitis, fracturas, orquitis, metritis, mastitis y cólicos; en cualquier proceso doloroso asociado a traumatismo o alteraciones neurológicas y en caso de reacciones inflamatorias producidas por shock séptico.' },
    // { name: 'ERITROGEN®', imageSrc: 'img/anestesicos/eritrogen.png', descripProdu: 'Indicaciones: En caso de anemias microciticas e hipocrómicas o producidas por hemorragias, para la recuperación después de parasitosis producida por: Tripanosoma, Anaplasma y Piroplasma, como reconstituyente después de infecciones bacterianas, virales y en animales después de la temporada de servicio.' }
];


// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});
