// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'KETAMINA 100 CHINFIELD', imageSrc: 'img/anestesicos/ketamina.png', descripProdu: '<h3>Indicaciones:</h3><br>Anestésico General de uso solo o como inductor de anestesia general con agentes inhalatorios. Ketamina es un anestésico general de rápida acción con una significativa acción analgésica y ausencia de efectos depresores del sistema cardiorrespiratorio. Inhibe la transmisión de los impulsos a través del sistema reticular lo que impide la llegada de los mismos a la corteza cerebral. Esto induce un nivel de anestesia de grado I y II pero no estado III. En felinos induce una pequeña hipotermia con una disminución de la temperatura del orden de 1.5 a 1.7°C después de una dosis terapéutica.<h3>Dosis y Administración:</h3><br>Equinos: (en ml) Endovenosa: 3 a 5 ml x 100kpv Bovinos: (en ml) Endovenosa 5 ml x 100 kpv. Porcinos: (en ml) Endovenosa: 0,5 ml x 10 kpv. Intramuscular: 1 a 2 ml x 10 kpv. Ovinos: (en ml) Endovenosa: 0,3 ml x 10 kpv. Intramuscular: 1 a 2 ml x 10 kpv. Caninos y felinos: (en ml) Endovenosa: 0,07 a 0,1 ml x kpv. Intramuscular: 0,15 a 0,25 ml x kpv. Primates: (en ml) Endovenosa: 0,01 a 0,05 ml x kpv. Intramuscular: 0,05 a 0,15 ml x kpv.<h3>DOSIS TERAPÉUTICA:</h3><br>15 mg/kg mediante inyección intramuscular.<h3>Composición y especies:</h3><br>Ketamina 10 g Agentes de formulación c.s.p. 100 ml Equinos deportivos y de trabajo no destinados al consumo alimentario humano, bovinos, ovinos, porcinos, caninos, felinos, primates.<h3>Laboratorio:</h3><br> CHINFLED. Presentación: Estuche conteniendo 1 frasco ampolla x 50 ml. ' },
    { name: 'LIDOCAINA 2% CHINFIELD', imageSrc: 'img/anestesicos/LIDOCAINA.png', descripProdu: '<h3>Indicaciones:</h3><br>Anestesia infiltrativa, raquídea epidural, paravertebral, troncular. Anestesias diagnósticas en claudicaciones.<h3>Dosis y Administración:</h3><br>Intradérmico, subcutáneo, intramuscular, epidural, intraarticular. Anestesia local regional o troncular: En general para todas las especies: 0,3 mg/kpv. Equivalente a 0,15 ml/kpv. Anestesia epidural: Equinos: 2 a 4 ml cada 100 kg de peso para anestesia posterior con mantenimiento de la estación. Superando estas dosis, es esperable el decúbito del equino por bloqueo anterior. Caninos y Felinos: 1 ml cada 4,5 kg de peso bloquea hasta L1. 1 ml cada 3,4 kg bloquea hasta T5.<h3>DOSIS TERAPÉUTICA:</h3><br>0,3 mg/kpv.<h3>Composición y especies:</h3><br>Lidocaína clorhidrato 2 g Agentes de formulación c.s.p. 100 ml Equinos deportivos y de trabajo no destinados al consumo alimentario humano, caninos, felinos.<h3>Laboratorio:</h3><br> CHINFLED. Presentación: Estuche conteniendo 1 frasco ampolla x 100 ml.' },
    { name: 'XILAZIL (XILAZINA 10%)', imageSrc: 'img/anestesicos/XILAZIL.png', descripProdu: '<h3>Indicaciones:</h3><br>Para producir estado de sedación y analgesia. Como preanestésico de la anestesia general. En procedimientos diagnósticos: exámen bucal, oftálmico, ótico, vaginal. Palpación rectal. Sondeo nasogástrico, vesical. Diagnósticos por imágenes (radiográfía, ecografía, gastroscopía). En maniobras de desvasado y herrado. En cirugías menores que requieran sólo sedación y analgesia leve: caso de limpieza y suturas de heridas con asociación o no de anestésico local, aperturas de abscesos.<h3>Dosis y Administración:</h3><br>Endovenoso: 0,5 ml cada 50 kpv. Intramuscular: 0,5 – 1 ml cada 50 kpv. De ser necesario se puede repetir dosificación según criterio del Médico Veterinario. Se recomienda la utilización de la mitad de dosis inicial y de ser necesario una tercera aplicación, la mitad de la segunda.<h3>DOSIS TERAPÉUTICA:</h3><br>La dosificación oscila entre 1 – 3 mg de xilacina/kg por vía intramuscular o subcutánea. Si se emplea la vía intravenosa la dosificación oscila entre 0,5 – 1 mg de xilacina/kg.<h3>Composición y especies:</h3><br>Xilazina 10 g Agentes de formulación c.s.p. 100 ml Equinos deportivos y de trabajo no destinados al consumo alimentario humano.<h3>Laboratorio:</h3><br> CHINFLED. Presentación: Estuche conteniendo 1 frasco ampolla x 50 ml.' },
    { name: 'PENTA-HYPNOL®', imageSrc: 'img/anestesicos/PENTA.png', descripProdu: '<h3>Indicaciones:</h3><br>Anestésico barbitúrico de acción corta. Según la dosis, induce efectos sedantes, hipnóticos y de anestesia general en pequeñas especies (intervenciones quirúrgicas de hasta 2 horas de duración). Como sedante o hipnótico en grandes especies. En sobredosis, puede administrarse como eutanásico. Indicado además para el manejo de estados convulsivos causados por envenenamiento, eclampsia puerperal, epilepsia, entre otros.<h3>Dosis y Administración:</h3><br>Vía intravenosa. Caninos y felinos: 1 mL/2.5 kg de p.v. Bovinos y equinos: 1 mL/15 a 65 kg de p.v. Porcinos: 1 mL/2.5 kg de p.v. Caprinos y ovinos: como sedante o inductor de anestesia: aprox. 24 mg/kg de pentobarbital sódico, con un rango de 11 - 54 mg/kg.<h3>DOSIS TERAPÉUTICA:</h3><br>Caprinos y ovinos: como sedante o inductor de anestesia: aprox. 24 mg/kg de pentobarbital sódico, con un rango de 11 - 54 mg/kg. Caninos y felinos: 40 a 60 mg/kg de peso corporal cuando se inyecta por vía intravenosa.<h3>Composición y especies:</h3><br>Pentobarbital sódico 65 mg. Excipientes c.s.p. 1 mL Grandes y pequeñas especies.<h3>Laboratorio:</h3><br> AGROVET. Presentación: Frasco x 50 mL.' },
    { name: 'SUPRIVAN®', imageSrc: 'img/anestesicos/SUPRIVAN.png', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado como anestésico general en procedimientos quirúrgicos de periodos cortos en perros y gatos. En cirugías de larga duración puede usarse para inducir y mantener la anestesia con infusiones continuas de la droga. En caso de uso de anestesia inhalatoria, puede utilizarse como inductor de la anestesia general para la entubación endotraqueal. Puede usarse como anestésico en caso de diagnóstico ambulatorio o procedimientos menores (reparación de laceraciones, procedimientos radiológicos, odontología menor, biopsias menores, endoscopia, entre otros). Adicionalmente puede ser administrado para el tratamiento del estado refractario epiléptico.<h3>Dosis y Administración:</h3><br>Administrar únicamente por vía inyectable intravenosa. La dosis de inducción en perros cuando no se usa un pre anestésico es de 5.5 a 7.0 mg/kg (en la práctica 1 mL/1.4 a 1.8 kg), mientras que en gatos es de 8 a 13.2 mg/kg (en la práctica 1 mL/0.75 a 1.25 kg). Las dosis con diferentes pre anestésicos xilacina, acepromacina, medetomidina, ketamina entre otros se reducen drásticamente. Otras especies animales: entre 3 y 15 mg/kg.<h3>DOSIS TERAPÉUTICA:</h3><br>Caninos: 5.5 a 7.0 mg/kg. Felinos: 8 a 13.2 mg/kg (en la práctica 1 mL/0.75 a 1.25 kg). Otras especies animales: entre 3 y 15 mg/kg.<h3>Composición y especies:</h3><br>Propofol 10 mg. Excipientes c.s.p. 1 mL. Pequeñas especies.<h3>Laboratorio:</h3><br> AGROVET. Presentación: Frasco x 20 mL, Frasco x 30 mL, Frasco x 50 mL.' },
    { name: 'KET-A-XYL®', imageSrc: 'img/anestesicos/KET.png', descripProdu: '<h3>Indicaciones:</h3><br>La combinación de ketamina, xilacina y atropina ofrece un mejor resultado anestésico disminuyendo los efectos colaterales. Indicado en la inducción y mantenimiento de la anestesia en caninos, intervenciones quirúrgicas tales como ovariectomías, castraciones, cesáreas, operaciones en cavidad abdominal, extracciones dentales, operaciones en los ojos, entre otras. La adición de atropina evita el aumento de la salivación y otras secreciones excesivas, evita el espasmo laríngeo durante la intubación endotraqueal y previene los efectos bradicardizantes de la ketamina.<h3>Dosis y Administración:</h3><br>0.5 - 1 mL/10 kg de p.v. Aplicar solo vía intramuscular.<h3>DOSIS TERAPÉUTICA:</h3><br>0,3 mg/kpv.<h3>Composición y especies:</h3><br>Ketamina (clorhidrato) 100 mg Xilacina (clorhidrato) 20 mg Atropina sulfato (monohidrato) 1 mg Excipientes c.s.p. 1 mL.<h3>Laboratorio:</h3><br> AGROVET. Presentación: Frasco x 50 mL.' }
];



// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});

