// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'ANTRIFORMINT FM ®', imageSrc: 'img/antibioticos/ANTRIFORMINT.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de anaplasmosis y babesia en bovinos, búfalos, equinos, ovinos y caprinos. Antibiótico de amplio espectro. Polvo para reconstituir.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Bovinos, Búfalos, Ovinos y Caprinos: 1,5 ml por 20 kg de peso vivo. Equinos: dividir dosis y aplicar con intervalos de 2 horas para evitar síntomas de cólico.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Oxitetraciclina HCL ...... 200 mg Antipirina ...... 150 mg Diminaceno ...... 70 mg Excipientes c.s.p. ...... 100 ml ' },
    { name: 'ANTRIBAM 4G ®', imageSrc: 'img/antibioticos/ANTRIBAM.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos, búfalos, ovinos y caprinos para la prevención, tratamiento y control de la tripanosomiasis.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Polvo para reconstituir. Agítese antes de usar. Dosis preventiva: 1 ml por cada 80 kg de peso vivo. Dosis curativa: En zonas de baja incidencia 1 ml por cada 40 kg de peso vivo. En zonas de mediana o alta incidencia 2 ml por cada 40 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>0,5 mg<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Cloruro de isometamidium 4 g Diluyente estéril 200 ml' },
    { name: 'ASCEND ®', imageSrc: 'img/antibioticos/ascend.png', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado para la prevención y tratamiento de la piroplasmosis, anaplasmosis, ehrlichiosis, hepatozoonosis y citauxzoonosis.<h3>Dosis y Administración:</h3><br>Vía subcutánea o intramuscular. Bovinos, Ovinos y Caprinos: 1 - 2,5 ml por cada 100 kg de peso vivo. Equinos: 2 ml por cada 100 kg de peso vivo. Caninos: 0,5 ml por cada 10 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>1-5 mg<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Imidocarb Dipropionato 12 g Excipientes csp 100 ml' },
    { name: 'ENROFLOXACINA 10% ®', imageSrc: 'img/antibioticos/enrofloxasina.jpg', descripProdu: '<h3>Indicaciones:</h3><br>Para tratamiento de procesos infecciosos del aparato respiratorio, digestivo y genitourinario. Infecciones virales e infecciones de la piel causadas por gérmenes grampositivos, gramnegativos y micoplasma en Bovinos, Ovinos, Caprinos, Porcinos, Felinos y Caninos.<h3>Dosis y Administración:</h3><br>Vía subcutánea, intramuscular o intravenosa. (en el anca). Las ovejas y las cabras se inyectan en los músculos del muslo. Bovinos, Ovinos, Caprinos y Porcinos: 1 ml por cada 40 kg de peso vivo. En casos graves, aplicar 1ml por cada 20 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3> Cada 1 cm³ contienen: Enrofloxacina 100 mg Excipientes csp 1 ml' },
    { name: 'FLUXIPEN ®', imageSrc: 'img/antibioticos/fluxipen.png', descripProdu: '<h3>Indicaciones:</h3><br>Antibiótico de rápido efecto y prolongada acción en infecciones causadas por gérmenes sensibles a la penicilina. Suspensión inyectable estéril.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Dosis General: 1 ml por 20 kg de peso vivo. Aplicar 3 ml por cada 50 - 100 de peso vivo. Tratamiento: de 1 a 3 días consecutivos. Después de reconstruir es estable por 30 días en refrigeración.<h3>DOSIS TERAPÉUTICA:</h3><br>11.000 - 22.000 UI<h3>Composición y especies:</h3> Cada 1 cm³ contienen: Penicilina G sódica 4000000 UI Penicilina G Procaína 4000000 UI Sulfato de dihidroestreptomicina 5 mg Diclofenaco sódico 05 g Excipientes csp 1 ml' },
    { name: 'RESANIQ ®', imageSrc: 'img/antibioticos/RESANIQ.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos, ovinos, caprinos y porcinos en el tratamiento preventivo y curativo de infecciones respiratorias (pasteurelosis, neumonía, bronconeumonía, pleuroneumonía), infecciones urogenitales (cistitis, nefritis, metritis, síndrome MMA de las cerdas), infecciones cutáneas y tejidos blandos (pododermatitis abscesos) e infecciones postparto.<h3>Dosis y Administración:</h3><br>Vía intramuscular o subcutánea. Porcinos, Ovinos, Bovinos y Caprinos: 1 ml por cada 10 kg de peso vivo. Repetir la dosis a las 48 horas.<h3>DOSIS TERAPÉUTICA:</h3><br>10 mg<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Amoxicilina 15 g Excipientes CSP 100 ml' },
    { name: 'SONENIX 150®', imageSrc: 'img/antibioticos/sonenix.png', descripProdu: '<h3>Indicaciones:</h3><br>Para Bovinos, Porcinos, Caprinos y Ovinos en el tratamiento de mastitis infecciosa y pododermatitis en ganado bovino, tratamiento en infecciones respiratorias, urogenitales, gastrointestinales, de piel y tejidos blandos.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Bovinos: 1 ml por cada 15 a 20 kg de peso cada 24 horas entre 3 a 5 días Porcinos, Ovinos y Caprinos: 1 ml por cada 15 kg de peso entre 3 a 5 días. Cada 12 a 24 horas.<h3>DOSIS TERAPÉUTICA:</h3><br>15 mg<h3>Composición y especies:</h3>Cada 1 cm³ contiene: Cefalexina (Monohidrato) 150 mg Excipientes csp 1 ml' },
    { name: 'ENOMETROL®', imageSrc: 'img/antibioticos/Enometrol.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de infecciones respiratorias, genito-urinarias provocadas por bacterias gramnegativas y grampositivas. Infecciones de la cavidad oral y afecciones cutáneas.<h3>Dosis y Administración:</h3><br>Vía oral. 0,2 ml por cada kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>La dosis máxima que se debe administrar es de 50 - 65 mg/kg por día en cualquier especie.<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Enrofloxacina Base 2,5 g Metronidazol Benzoato 8 g Excipientes csp 100 ml' },
    { name: 'AMOXIGEN', imageSrc: 'img/antibioticos/amoxigen.png', descripProdu: '<h3>Indicaciones:</h3><br>Bovinos: Infecciones causadas por bacterias sensibles a la combinación de Amoxicilina y Gentamicina, como las presentes en neumonías, enteritis bacteriana, mastitis, metritis y abscesos cutáneos.<h3>Dosis y Administración:</h3><br>Intramuscular Profunda. 1 ml por 10 kg de peso, durante 3 días. bajo supervisión del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>10 mg<h3>Composición y especies:</h3> Contiene por ml: 100 ml y 250 ml Amoxicilina Trihidrato 150 mg. Gentamicina base 40 mg Excipientes c.s.p. 1 ml. <br> <br> <br> Bovinos, Porcinos.' },
    { name: 'OXITETRACICLINA AL 5%', imageSrc: 'img/antibioticos/OXITETRACICLINA.png', descripProdu: '<h3>Indicaciones:</h3><br>Bovinos: para tratar Anaplasmosis, Lesiones Pódales, Leptospirosis, Metritis, sensibles a Oxitetraciclina. Porcinos: para tratar el Síndrome Mastitis Metritis Agalactia (MMA), Neumonía, Lesiones Pódales, sensibles a Oxitetraciclina. Ovinos: para tratar Pasteurelosis, Clamidiasis, Neumonía, Lesiones Pódales, sensibles a Oxitetraciclina. Aves: para tratar Coriza, Colera, Enfermedad Crónica Respiratoria (ECR), sensibles a Oxitetraciclina.<h3>Dosis y Administración:</h3><br>Intramuscular profunda. 500 cm3 En general 1 cm3 por cada 5 kg de peso vivo. Aves: 0,5 cm3 a 1 cm3 por ave adulta (2,5 a 5kgs) repetir cada 24 horas o a criterio del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3> Oxitetraciclina 50 mg Bovinos, Porcinos, Caprinos, Ovinos, Equinos, Aves.' },
    { name: 'FLORFENICOL L.A.', imageSrc: 'img/antibioticos/FLORFENICOL.png', descripProdu: '<h3>Indicaciones:</h3><br>Antibiótico de amplio espectro que actúa contra bacterias gram positivas y gram negativas del ganado bovino, ovino, caprino, porcino y aves, como: Pasteurellas, Haemophylus somnus, Klebsiella sp., Escherichia coli, Moraxella sp., Salmonella sp., Bacteroides sp., Fusobacterium sp., Corynebacterium pyogenes, Clostridium sp., Streptococcus, causantes de infecciones como neumonías, pododermatitis, metritis, enteritis y en general, procesos susceptibles a bacterias sensibles al Florfenicol.<h3>Dosis y Administración:</h3><br>Subcutánea o intramuscular preferiblemente en la tabla del cuello. Bovinos, Ovinos y Caprinos: 1 ml por cada 20 Kg de peso (20 mg/kg), una segunda aplicación a las 48 horas 1 ml por cada 10 Kg de peso (40 mg/kg). 30 ml Porcinos: 1 ml por cada 25 a 30 Kg de peso (15 mg/Kg), una segunda aplicación a las 48 horas. Aves: 0,15 ml por cada 2 Kg de peso. Esta dosis puede ser modificada por el Médico Veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>4-11 mg. IM/IV 2-4 mg.<h3>Composición y especies:</h3> Cada 100 ml contiene: Florfenicol 400 mg Vehículo c.s.p. 1 ml Bovinos, Porcinos, Caprinos, Ovinos, Aves.' },
    { name: 'SULFACET', imageSrc: 'img/antibioticos/SULFACET.png', descripProdu: '<h3>Indicaciones:</h3><br>Sirve para combatir infecciones generales, agudas o crónicas, causadas por bacterias gram negativas o positivas, sensibles a la formulación en bovinos, equinos, ovinos, caprinos y porcinos. Esta indicado en Neumonías, Bronquitis Infecciosas, Difterias de los terneros, Enteritis Bacilar, Septicemia Hemorrágica, Metritis Séptica y Retención Placentaria; Mastitis Aguda, Poliartritis, Colibacilosis, Flemones y Abscesos, en infecciones secundarias de la Diarrea Blanca del ternero y como auxiliar en el tratamiento de la “Chinela» y en cualquier otra infección donde este indicado el tratamiento sulfamídico.<h3>Dosis y Administración:</h3><br>Intravenosa ó intramuscular. En Bovinos, Equinos, Ovinos, Caprinos y Porcinos, como dosis inicial o de ataque, de 25 a 40 ml por cada 100 Kg de peso según criterio del facultativo. Después como dosis de mantenimiento, la mitad de la dosis inicial, diariamente por un término de 5 días. 250 ml Retiro en carne 3 días y retiro en leche 7 días.<h3>DOSIS TERAPÉUTICA:</h3><br>25 mg<h3>Composición y especies:</h3> Cada 100 ml. contiene: Sulfadiazina Sódica 8.5 g Sulfadimidina Sódica 8 g Sulfamerazina Sódica 8.5 g Dextrosa Anhidra 15 g Excipientes c.s.p. 100 ml Bovinos, Equinos, Ovinos, Caprinos y Porcinos.' },
    { name: 'CEPTIFUR 100 ml', imageSrc: 'img/antibioticos/CEPTIFUR.png', descripProdu: '<h3>Indicaciones:</h3><br>Porcinos: Tratamiento curativo de infecciones respiratorias causadas por Actinobacillus pleuropneumoniae, Pasteurella multocida y Streptococcus suis. Bovinos: Tratamiento curativo de infecciones respiratorias causadas por Pasteurella haemolytica, P. multocida y Haemophilus somnus; de la pododermatitis infecciosa causada por Fusobacterium necrophorum y Bacteroides melaninogenicus; y de la metritis aguda post-parto en los 10 días después del parto asociada con E. coli, Arcanobacterium pyogenes y Fusobacterium necrophorum.<h3>Dosis y Administración:</h3><br>Porcinos: 1 ml/16 kg p.v(3 mg de Ceftiour/kg p.v), por vía intramuscular, durante 3 días. Bovinos: 1 ml/50 kg p.v(1 mg de Ceftiofur/kg p.v), por vía subcutánea, durante 3 a 5 días.<h3>DOSIS TERAPÉUTICA:</h3><br>5 mg<h3>Composición y especies:</h3> Ceftiofur (clorhidrato) 50 mg Excipiente c.s.p. 1 ml Bovinos y porcinos.' },
    { name: 'DIHIDROESTREX', imageSrc: 'img/antibioticos/DIHIDROESTREX.png', descripProdu: '<h3>Indicaciones:</h3><br>Antibiótico de acción bactericida, principalmente sobre bacterias gran negativas.<h3>Dosis y Administración:</h3><br>Intramuscular profunda. Bovinos y Porcinos: 1 ml/10kg p.v. (50 mg de Dihidroestreptomicina/kg p.v.) en dosis única. Equinos, Ovinos y Caprinos: 0,5 ml/kg p.v./día durante tres días. Perros: 0,1 ml/kg p.v. (50 mg de Dihidroestreptomicina/kg p.v.) /día durante 3 días. Aves: 50 o 100 mg/kg p.v. del producto diluido 1:10 o 1:20 diluido con agua para inyección.<h3>DOSIS TERAPÉUTICA:</h3><br>11 mg<h3>Composición y especies:</h3> Dihidroestreptomicina 50 mg Excipientes 100 ml Bovinos, ovinos, caprinos, caninos, equinos y aves.' },
    { name: 'DIMINAZENE-A', imageSrc: 'img/antibioticos/DIMINAZENe.png', descripProdu: '<h3>Indicaciones:</h3><br>Tratamiento curativo de la Tripanosomiasis bovina causada por Trypanosoma vivax. Tratamiento curativo de la Tripanosomiasis equina causada por Trypanosoma evansi, también conocido como T.equinum, T. hippicum y T. venezuelense. Tratamiento curativo de la Babesiosis (Piroplasmosis) bovina y equina. Tratamiento curativo de infecciones mixtas por tripanosomas y babesias en ambas especies.<h3>Dosis y Administración:</h3><br>Administrar por vía intramuscular profunda. Bovinos y Equinos: 1 ml/20 kg p.v(3,5 mg de Diminazene diaceturato/kg p.v). En caso necesario, repetir la dosis cada 24 horas.<h3>DOSIS TERAPÉUTICA:</h3><br>7 mg<h3>Composición y especies:</h3> Diminazeno diaceturato 7g Antipirina 25g Excipiente c.s.p. 100 ml Bovinos y Equinos.' },
    { name: 'MASTIVEEX RETARD X4', imageSrc: 'img/antibioticos/MASTIVEEX.png', descripProdu: '<h3>Indicaciones:</h3><br>Vacas: Tratamiento de las mastitis en el periodo de secado causadas por Staphylococcus aureus, Streptococcus agalactiae, Streptococcus dysgalactiae, Streptococcus uberis, E. coli y otras especies de gérmenes sensibles a la asociación. Prevención de nuevas infecciones durante el periodo de secado.<h3>Dosis y Administración:</h3><br>Vía Intramamaria. Aplicar el contenido completo de 1 inyector por cada cuarto, inmediatamente después del último ordeño.<h3>Composición y especies:</h3> Cloxacilina (benzatina) 400 mg Framicetina (sulfato) 200 mg Excipiente c.s.p. 1 inyector de 10g Vacas, cabras, ovejas.' },
    { name: 'MASTIVEEX 1+ GENTAMICINA', imageSrc: 'img/antibioticos/MASTIVEEX1.png', descripProdu: '<h3>Indicaciones:</h3><br>Vacas: Tratamiento curativo de las mastitis en periodo de lactación causadas por Staphylococcus aureus, Streptococcus dysgalactiae, Streptococcus uberis, E. coli y otras especies de gérmenes sensibles a esta asociación.<h3>Dosis y Administración:</h3><br>Vía Intramamaria. Tratar desde la aparición de los primeros síntomas de mastitis. Vacas: Aplicar el contenido completo de 1 inyector por cuarto afectado, cada 24 horas, hasta la completa remisión de los síntomas.<h3>Composición y especies:</h3> Cloxacilina (sódica) 250 mg Framicetina (sulfato) 200 mg Sulfadimeracina (sódica) 500 mg Gentamicina (sulfato) 50 mg Quimotripsina 8 mg Excipiente c.s.p. 1 inyector de 10 g Vacas.' },
    { name: 'OXITETRACICLINA L.A. ®', imageSrc: 'img/antibioticos/OXITETRACICLINAL.A.png', descripProdu: '<h3>Indicaciones:</h3><br>En procesos infecciosos causados por gérmenes grampositivos y gramnegativos que afectan los tractos: respiratorio, digestivo, genitourinario; infecciones de la piel; infecciones virales (moquillo) y anaplasmosis.<h3>Dosis y Administración:</h3><br>Intramuscular profunda. Bovinos, Ovinos, Caprinos y Porcinos: 1 mL por cada 10 kg. Cada 48 a 72 horas. Duración de tratamiento a juicio del facultativo.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3> Oxitetraciclina 20%' }
];




// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});
