// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'ERITROGEN®', imageSrc: 'img/antianemicos/eritrogen.png', descripProdu: '<h3>Indicaciones:</h3><br>En caso de anemias microciticas e hipocrómicas o producidas por hemorragias, para la recuperación después de parasitosis producida por: Tripanosoma, Anaplasma y Piroplasma, como reconstituyente después de infecciones bacterianas, virales y en animales después de la temporada de servicio. Estimulante de la producción de carne y leche. Para tratar estados depresivos.<h3>Dosis y Administración:</h3><br>Vía de administración, inyección: Intramuscular, Intravenosa lenta y subcutánea. Bovinos y Equinos: 4 mL por cada 100 Kg. Porcinos, Ovinos y Caprinos: 1 mL por cada 25 Kg. En Bovinos, Ovinos, Caprinos y Porcinos se recomienda aplicar de 3 a 5 inyecciones a intervalo de 48 a 72 horas. Para la preparación de animales de concurso 1 a 2 inyecciones por cada semana durante 1 mes previo al evento.<h3>DOSIS TERAPÉUTICA:</h3><br>1-4ml/25-100kpv.<h3>Composición y especies:</h3><br>Hierro, cobre, cobalto, magnesio, vitamina B, aminoácidos, A.T.P y Dinitrilo succínico.<h3>Laboratorio:</h3><br>Presentación: Frascos de 100 y 500 mL.' },
    { name: 'MIVIFOS®', imageSrc: 'img/antianemicos/MIVIFOS.png', descripProdu: '<h3>Indicaciones:</h3><br>En deficiencia de fósforo y vitaminas del complejo B, mejora el desempeño reproductivo, en caso de anestro, en miopatías, para la recuperación de animales agotados (trabajo o parto) y en animales convalecientes luego de padecer enfermedades infecciosas y orgánicas. Otras indicaciones a criterio del Médico Veterinario.<h3>Dosis y Administración:</h3><br>Intramuscular profunda. Bovinos, equinos, ovinos, caprinos y porcinos: 2 mL / 50 Kg de peso. Caninos: hasta 10 Kg: 1,0 mL; de 10 a 20 Kg :2 mL y más de 20 Kg: 3 mL. Cada 24 horas, por 2 a 3 días.<h3>DOSIS TERAPÉUTICA:</h3><br>4.72 mg/kpv.<h3>Composición y especies:</h3><br>Fósforo 6,4 % y vitaminas del complejo B.<h3>Laboratorio:</h3><br>Presentación: Frascos de 500 mL.' },
    { name: 'FERRON B12', imageSrc: 'img/antianemicos/FERRONB12.png', descripProdu: '<h3>Indicaciones:</h3><br>Indicado para la prevención y el tratamiento de anemias ferropénicas, especialmente en lechones recién nacidos. En todas las especies, se recomienda para el tratamiento de la anemia por la deficiencia de hierro originada por diversas causas: la falta de mineral en el alimento, defectos en la absorción del hierro a través de la babesiosis, seguido de un tratamiento específico.<h3>Dosis y Administración:</h3><br>Para las anemias de los animales lactantes: Lechones (del 3er. hasta el 7mo. día de vida): 1 a 2 ml. Terneros (hasta 10mo. día de vida): 2 a 5 ml. Para el tratamiento de las Anemias Ferropénicas en todas las especies: Bovinos Adultos: 10 ml. Ovinos, Porcinos, Terneros: 5 ml.<h3>DOSIS TERAPÉUTICA:</h3><br>100–200 mg/kpv.<h3>Composición y especies:</h3><br>Cada ml contiene: Hierro Dextrano, equivalente a 100 mg Hierro Elemental 500,0 mg Fenol 5,0 mg Vitamina B12 10,0 mcg Vehículo Acuoso c.s.p. 1,0 ml<h3>Laboratorio:</h3><br>Presentación: Frasco con 50 ml y 100 ml.' },
    { name: 'FERROVIT 100', imageSrc: 'img/antianemicos/FERROVIT100.png', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado en el tratamiento y prevención de anemias por deficiencia de hierro en Lechones, (ANEMIA FERROPRIVA), así como en Bovinos, Ovinos, Caprinos, Equinos, Caninos y Felinos jóvenes y adultos. También Como coadyuvante en tratamientos que requieren de estimulación de la hematopoyesis como Tripanosomiasis, Babeciosis y Anaplasmosis.<h3>Dosis y Administración:</h3><br>Intramuscular Profunda. Lechones: 2 cm3, al tercer día de nacidos. Terneros: 4 a 8 cm3, durante la primera semana de vida. Corderos y Cabritos: 5 cm3. Bovinos y equinos adultos: 10 a 20 cm3.<h3>DOSIS TERAPÉUTICA:</h3><br>200 mg/animal en dosis única.<h3>Composición y especies:</h3><br>Hierro Dextrano y Vitamina B12. Bovinos – Equinos – Ovinos – Caprinos – Caninos – Felinos – Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos de 100 y 250 cm3.' },
    { name: 'SUIFERRO FUERTE', imageSrc: 'img/antianemicos/SUIFERROFUERTE.png', descripProdu: '<h3>Indicaciones:</h3><br>Anemias. Animales en crecimiento. Falta de desarrollo. Convalecencias de enfermedades anemizantes infecciosas o parasitarias. Pérdida de peso. Parasitosis gastrointestinales. Preñez, Lactancia. Pre y post destete.<h3>Dosis y Administración:</h3><br>Bovinos: Subcutánea en la tabla del cuello. 1 a 2 ml cada 100 Kg de peso. Porcinos: Subcutánea o intramuscular por detrás del cuello. 0,3 ml cada 5 Kg de peso. Repetir cada 30 – 45 días según necesidad. Dosis e intervalos pueden ser modificados según criterio del Médico Veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>50 mg/kg de peso por infusión IV.<h3>Composición y especies:</h3><br>Edetato de Sodio y Hierro 10.000 mg Edetato de Sodio y Cobalto 5.000 mg Edetato de Sodio y Cobre 50 mg Agentes de formulación c.s.p. 100 ml Bovinos y porcinos.<h3>Laboratorio:</h3><br>Presentación: Frasco x 250 ml.' },
    { name: 'B12 50,000 MCG', imageSrc: 'img/antianemicos/B12.png', descripProdu: '<h3>Indicaciones:</h3><br>Anemias (disminución del número de glóbulos rojos) de cualquier tipo. Procesos neurológicos (neuralgias, neuritis). Convalecencias. Debilidad. Tónico inespecífico. Para ayudar a la recuperación de animales parasitados.<h3>Dosis y Administración:</h3><br>5 a 10 ml diarios, día por medio o más distanciados o según indicación del Médico Veterinario. Inyección intramuscular o endovenosa LENTA.<h3>DOSIS TERAPÉUTICA:</h3><br>100–200 mg/kpv.<h3>Composición y especies:</h3><br>Vitamina B12 50.000 µg Agentes de formulación c.s.p. 50 ml Equinos deportivos y de trabajo no destinados al consumo alimentario humano.<h3>Laboratorio:</h3><br>Presentación: Estuche conteniendo 1 frasco ampolla x 50 ml.' },
    { name: 'HEMOFIELD', imageSrc: 'img/antianemicos/HEMOFIELD.png', descripProdu: '<h3>Indicaciones:</h3><br>Antianémico. Antineurítico. Vitaminoterapias. Animales expuestos a enfermedades infecciosas o parasitarias anemizantes.<h3>Dosis y Administración:</h3><br>Equinos en crecimiento: 2,5 ml cada 100 kg de peso diarios. Equinos adultos: 10 ml diarios. Caninos: 1 ml cada 25 kg de peso diarios. Aplicar, preferentemente, por vía endovenosa LENTA. También se puede aplicar por vía intramuscular.<h3>DOSIS TERAPÉUTICA:</h3><br>2-8mg/kpv.<h3>Composición y especies:</h3><br>Ácido fólico 0,1 g Vitamina B1 10 g Vitamina B12 0,2 g Agentes de formulación c.s.p. 100 ml Equinos deportivos y de trabajo no destinados al consumo alimentario humano, caninos.<h3>Laboratorio:</h3><br>Presentación: Estuche conteniendo 1 frasco ampolla x 50 ml.' }
];




// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});

