// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'BOLICOL', imageSrc: 'img/antidiarreicos/BOLICOL.png', descripProdu: '<h3>Indicaciones:</h3><br>Diarreas de origen bacteriano o tóxico. Enteritis. Gastroenteritis. Meteorismo. Infecciones alimentarias.<h3>Dosis y Administración:</h3><br>Equinos adultos: 100 ml cada 100 kpv. Potrillos, terneros y corderos hasta 2 meses de edad, porcinos: 2 ml cada kpv. Caninos y Felinos: 2 ml cada kpv. Vía oral, directamente en la boca o por sonda nasogástrica puro o mezclado en el momento con agua.<h3>DOSIS TERAPÉUTICA:</h3><br>50 a 100mg/kg.<h3>Composición y especies:</h3><br>Ftalilsulfatiazol 2,6 g Dihidroestreptomicina sulfato 0,51 g Metilbromuro de Homatropina 0,5 mg Dimetilpolisiloxano 1,0 g Carbon ultraactivado 0,5 g Agentes de formulación c.s.p. 100 ml Equinos deportivos y de trabajo no destinados al consumo alimentario humano, potrillos, terneros, porcinos, ovinos, caninos, felinos.<h3>Laboratorio:</h3><br>Presentación: Frasco x 1000 ml. Bidón x 5 litros.' },
    { name: 'STOP ANTI-DIARRÉICO', imageSrc: 'img/antidiarreicos/STOP.png', descripProdu: '<h3>Indicaciones:</h3><br>Contiene Pectina (ayuda en la protección gastrointestinal). Bactericida y Bacteriostático. Facilidad en la aplicación. Asociación consagrada.<h3>Dosis y Administración:</h3><br>Aviar, Caninos y Felinos: 1 sobre para cada 100 Kg de peso vivo (100 mg/kg). Bovinos, Equinos, Ovinos, Caprinos y Porcinos: 1 sobre para cada 142 Kg de peso vivo (70 mg/kg). Administrar en intervalos de 24 horas y mantener el tratamiento hasta 48 horas después de cesar los síntomas clínicos, o a criterio del Médico Veterinario. El tratamiento no debe exceder 7 días. Puede ser mezclado con la ración, o disuelto en agua de bebida o leche, cuidar para que el animal ingiera la cantidad total de la dosis en cada toma. Diluir el contenido del sobre (10 gr) en la cantidad de líquido (agua o leche) que el técnico o veterinario tratante considere correlativo al peso corporal del animal o animales a tratar.<h3>DOSIS TERAPÉUTICA:</h3><br>70-100mg/kpv.<h3>Composición y especies:</h3><br>Cada 10 mg contiene: Sulfametoxazol 1,00 g Trimetoprim 0,08 g Pectina 1,80 g Excipiente c.s.p. 10,00 g Bovinos – Equinos – Ovinos – Caprinos – Aves – Caninos – Felinos – Porcinos.<h3>Laboratorio:</h3><br>Presentación: Caja con 10 Sobres de 10 g c/u.' },
    { name: 'CARBATAN', imageSrc: 'img/antidiarreicos/CARBATAN.png', descripProdu: '<h3>Indicaciones:</h3><br>Carbatan es un antidiarreico muy usado en casos de: Disentería, Meteorismo, Flatulencia, “Cursos” / Diarrea blanca del ternero recién nacido y como poderoso coadyuvante en el tratamiento de la peste “Boba” o “Bobita”, en los terneros.<h3>Dosis y Administración:</h3><br>Vía oral. Adminístrese en cucharadas rasas; mezclando con agua o en el alimento: Bovinos y Caballos: 2 a 3 cucharadas, dos veces al día. Vía oral. Terneros y Potros: 2 cucharadas, dos veces al día. Vía oral. Ovejas, Cabras, Perros y Lechones: 1 cucharada, dos veces al día. Vía oral. Gatos: 1/2 cucharada dos veces al día.<h3>DOSIS TERAPÉUTICA:</h3><br>3.200-6.400 UI de neomicina/kg p.v./día (equivalente a 32 - 64 mg de medicamento/kg p.v./día).<h3>Composición y especies:</h3><br>Cada 100 g. contiene: Neomicina Sulfato 100 mg Yodoclorohidroxiquinoleina 3 g Succinilsulfatizol 10 g Acido Tánico 10 g Carbón Vegetal 47 g Excipiente c.s.p. 100 g Bovinos, Equinos, Ovinos, Caprinos, Caninos y Felinos.<h3>Laboratorio:</h3><br>Presentación: Frasco de 300 gr.' },
    { name: 'DIARREX H', imageSrc: 'img/antidiarreicos/DIARREX.png', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado en el tratamiento de Diarreas, Ileitis, Clostridiosis, y Enteritis Hemorrágicas, Colibacilosis, y Salmonelosis, producidas por Clostridium, Estreptococos, Estafilococos, y Protozoarios (Serpulina Hyodysenteriae).<h3>Dosis y Administración:</h3><br>Intramuscular Profunda. 1 ml por cada 10Kg de peso vivo durante 3 a 4 Días. Dosis superior a 15ml repartir en dos puntos de aplicación. A criterio del Médico Veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>15 a 24 mg/kg.<h3>Composición y especies:</h3><br>Sulfonamida asociada. Bovinos, Bufalinos, Caprinos, Ovinos, Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos de 100 ml.' },
    { name: 'COLIJET 200', imageSrc: 'img/antidiarreicos/COLIJET.png', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado en el tratamiento de desórdenes infecciosos gastrointestinales en general provocados por bacterias como Salmonella, Shigella, Escherichia Coli.<h3>Dosis y Administración:</h3><br>Vía oral. 5 ml por cada 10 kg de peso vivo diarios de 3 a 5 días, A criterio del Médico Veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>15 a 24 mg/kg.<h3>Composición y especies:</h3><br>Sulfonamida. Bovinos, Bufalinos, Caninos, Caprinos, Ovinos, Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos de 200 ml. Frascos de 1 Litro.' },
    { name: 'LOPERAMIDA OVER', imageSrc: 'img/antidiarreicos/loperamida.png', descripProdu: '<h3>Indicaciones:</h3><br>Tratamiento sintomático de diarrea aguda y crónica.<h3>Dosis y Administración:</h3><br>Vía oral. 1 gota por k.p.v.<h3>Composición y especies:</h3><br>Cada 100 ml contiene: Loperamida clorhidrato 0,2 g Agentes de formulación c.s. Caninos y felinos.<h3>Laboratorio:</h3><br>Presentación: Frasco gotero con 10 ml de contenido neto.' },
    { name: 'NEOSULF', imageSrc: 'img/antidiarreicos/neosulf.png', descripProdu: '<h3>Indicaciones:</h3><br>Tratamiento y control de diarreas polimicrobianas, colibacilosis, enteritis, gastroenteritis, diarreas fermentativas, y enteritis por intoxicación alimenticia. Coadyuvante en el tratamiento de enteritis parasitarias y víricas.<h3>Dosis y Administración:</h3><br>Vía oral. 1 ml por k.p.v.<h3>DOSIS TERAPÉUTICA:</h3><br>50 a 100mg/kg.<h3>Composición y especies:</h3><br>Cada 100 ml contiene: Ftalilsulfatiazol 2,5 g Estreptomicina sulfato 0,5 g Emulsión de Dimetilpolisiloxano al 10% 1 g Caolín coloidal 1,5 g Agentes de formulación c.s. Caninos y felinos.<h3>Laboratorio:</h3>' }
];




// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});

