// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'EXCELL 10', imageSrc: 'img/biologicos/EXCELL.png', descripProdu: '<h3>Indicaciones:</h3><br>Para la prevención del Carbunco Sintomático, Gangrena Gaseosa, Muerte Súbita, Enterotoxemia de los ovinos (enfermedad del riñón pulposo), Edema Maligno, Tétanos y Botulismo.<h3>Dosis y Administración:</h3><br>Subcutánea o intramuscular. Bovinos: 5 mL. Ovinos, caprinos y porcinos: 2 mL.<h3>Composición y especies:</h3><br>Anacultivos de Clostridium chauvoei y toxoides inactivados de Clostridium novyi B, Clostridium sordellii, Clostridium perfringens B, C y D, Clostridium septicum, Clostridium tetani, y Clostridium botulinum C y D. Adjuvante: Hidróxido de aluminio. Bovinos, Caprinos, Ovinos, Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos de 50, 100 y 250 mL, equivalente a 10, 20 y 50 dosis.' },
    { name: 'LEPTOVEN 10', imageSrc: 'img/biologicos/LEPTOVEN.png', descripProdu: '<h3>Indicaciones:</h3><br>Para la prevención de la leptospirosis en bovinos, porcinos, ovinos y caprinos.<h3>Dosis y Administración:</h3><br>Subcutánea. La dosis es de 2 mL para todas las especies indicadas.<h3>Composición y especies:</h3><br>Cultivos inactivados de Leptospira interrogans serovar pomona, L. interrogans serovar canicola, L. interrogans serovar icterohaemorrhagiae, L. interrogans serovar wolffii, L. interrogans serovar grippotyphosa, L. interrogans serovar tarassovi, L. interrogans serovar hardjo, L. interrogans serovar bataviae, L. interrogans serovar copenhageni, y L. interrogans serovar pyrogenes. Adjuvante: Hidróxido de aluminio. Bovinos, Caprinos, Ovinos, Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos de 50 mL (25 dosis).' },
    { name: 'MASTER SORO PLUS', imageSrc: 'img/biologicos/MASTER.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de envenenamiento causado por serpientes del género Bothrops (Mapanare), Lachesis (Cuaima piña) y Crotalus (Cascabel).<h3>Dosis y Administración:</h3><br>Casos benignos: aplicar 1 frasco del producto reconstituido por vía subcutánea. Casos graves: aplicar 3 frascos o más del producto reconstituido, por vía subcutánea, intramuscular o endovenosa a criterio del Médico Veterinario. Los accidentes causados por Crotalus son considerados casos graves.<h3>Composición y especies:</h3><br>Solución de inmunoglobulinas purificadas, concentradas y liofilizadas obtenidas a partir del plasma de equinos normales hiperinmunizados con venenos de serpientes de los géneros Bothrops (Mapanare), Lachesis (Cuaima piña) y Crotalus (Cascabel). Bovinos, Caninos, Caprinos, Equinos, Felinos, Ovinos, Porcinos.<h3>Laboratorio:</h3><br>Presentación: Estuche que contiene: 1 frasco de liofilizado y 1 frasco con 20 mL de diluyente.' },
    { name: 'SERKEL PNEUMO', imageSrc: 'img/biologicos/SERKEL.png', descripProdu: '<h3>Indicaciones:</h3><br>La vacuna SERKEL-PNEUMO es un inmunobiológico inactivado con adyuvante de hidróxido de aluminio, formulado para la prevención de la neumonía enzootica porcina provocada por Mycoplasma hyopneumoniae.<h3>Dosis y Administración:</h3><br>El producto debe ser aplicado por vía intramuscular, observando los cuidados de asepsia en lugar de inyección. Dosis: 2 mL. Lechones: Vacunar a los 21 días de edad dosis única. Período de retiro: cero días.<h3>Composición y especies:</h3><br>Bacterina de Mycoplasma hyopneumoniae 104 gérmenes. Excipientes c.s.p. 2 mL Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos 100 mL /50 dosis.' },
    { name: 'SUPRAVAC 10', imageSrc: 'img/biologicos/SUPRAVAC.png', descripProdu: '<h3>Indicaciones:</h3><br>Para la prevención de enfermedades respiratorias y reproductivas bovinas causadas por los virus BVD (Diarrea Viral Bovina), IBR (Rinotraqueítis Infecciosa Bovina), BRSV (Virus Respiratorio Sincicial Bovino), PI3 (Parainfluenza Bovina tipo 3) y por las bacterias Pasteurella haemolytica, Leptospira pomona, L. canicola, L. icterohaemorrhagiae, L. hardjo, L. wolffii y L. grippotyphosa.<h3>Dosis y Administración:</h3><br>Subcutánea. 5 mL.<h3>Composición y especies:</h3><br>Virus inactivados de BVD-Diarrea Viral Bovina Tipo 1 y BVD Diarrea Viral Bovina Tipo 2, IBR-Rinotraqueítis Infecciosa Bovina, BRSV-Virus Respiratorio Sincicial Bovino, PI3-Parainfluenza Bovina tipo 3 y bacterinas inactivadas de Pasteurella haemolytica, Leptospira pomona, L. canicola, L. icterohaemorrhagiae, L. hardjo, L. wolffii y L. grippotyphosa. Adjuvante: Hidróxido de aluminio. Bovinos.<h3>Laboratorio:</h3><br>Presentación: Frascos de 50 mL (10 dosis).' },
    { name: 'AFTOVAC', imageSrc: 'img/biologicos/AFTOVAC.png', descripProdu: '<h3>Indicaciones:</h3><br>Prevención y control de la fiebre aftosa en rumiantes.<h3>Dosis y Administración:</h3><br>Vía subcutánea. Administrar 2 mL.<h3>Composición y especies:</h3><br>Vacuna inactivada, emulsionada en aceite, elaborada con los serotipos A24 y 01 de virus causante de la enfermedad. Rumiantes.<h3>Laboratorio:</h3><br>Presentación: Frasco de 106 mL, 53 dosis.' },
    { name: 'RAVAX (CEPA ERA INACTIVADA)', imageSrc: 'img/biologicos/RAVAX.png', descripProdu: '<h3>Indicaciones:</h3><br>Prevención y control de la rabia en Bovinos, Equinos, Ovinos, Caprinos, Caninos y Felinos.<h3>Dosis y Administración:</h3><br>Vía subcutánea o intramuscular. Aplicar 2 mL. Primovacunar a los 3 meses de edad. Revacunar anualmente.<h3>Composición y especies:</h3><br>Vacuna inactivada adsorbida en gel de hidróxido de aluminio, elaborado con la cepa ERA multiplicada en cultivo celular. Bovinos, Equinos, Ovinos, Caprinos, Caninos y Felinos.<h3>Laboratorio:</h3><br>Presentación: Frasco de 106 mL, 53 dosis.' },
    { name: 'ESTOMAVAC BIVALENTE', imageSrc: 'img/biologicos/ESTOMAVAC.png', descripProdu: '<h3>Indicaciones:</h3><br>Prevención y control de la estomatitis vesicular en los Bovinos.<h3>Dosis y Administración:</h3><br>Vía I.M. en la tabla del cuello. Aplicar 3 mL. Primovacunación a los 3 meses de edad. Repetir de 3 a 4 semanas y revacunar a los 6 meses.<h3>Composición y especies:</h3><br>Contiene el virus de la Estomatitis Vesicular, serotipos New Jersey e Indiana, desarrollados en cultivos celulares. Bovinos.<h3>Laboratorio:</h3><br>Presentación: Frasco de 150 mL (50 dosis).' },
    { name: 'BOVISAN V4J5', imageSrc: 'img/biologicos/BOVISAN.png', descripProdu: '<h3>Indicaciones:</h3><br>Vacuna para ganado bovino que previene enfermedades infecciosas tanto bacterianas como virales del tracto respiratorio y digestivo.<h3>Dosis y Administración:</h3><br>Vía subcutánea o intramuscular. Dosis 5 mL.<h3>Composición y especies:</h3><br>Antígeno Concentración Mannheimia haemolytica 109 ufc Pasteurella multocida tipo A 109 ufc Escherichia coli K99 109 ufc Escherichia coli J5 109 ufc Salmonella dublin 109 ufc Virus Herpes Bovino tipo 1 (BHV-1) ≥ 106,5 DICT50 () Virus Herpes Bovino tipo 5 (BHV-5) ≥ 106,5 DICT50 () Virus Diarrea Viral Bovina tipo 1 (BVDV-1) ≥ 106 DICT50 () Virus Diarrea Viral Bovina tipo 2 (BVDV-2) ≥ 106 DICT50 () Virus Parainfluenza Bovina tipo 3 (BPI-3) ≥ 106 DICT50 () Virus Sincicial Respiratorio Bovino (BRSV) ≥ 105 DICT50 () Timerosal 0.25 mg Hidróxido de aluminio 0.75 mL Suero fisiológico c.s.p. 5.0 mL<h3>Laboratorio:</h3><br>Presentación: Frasco de 100 mL, contiene 20 dosis.' },
    { name: 'CLOSTRISAN ® 9+T', imageSrc: 'img/biologicos/CLOSTRISAN.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el control de muerte súbita causada por enfermedades Clostridiales, incluyendo tétanos. Prevenir las enfermedades clostridiales (mal de paleta, pierna negra, gangrena gaseosa, enteritis hemorrágica que provocan muerte súbita y tétanos en bovinos, ovinos, caprinos.<h3>Dosis y Administración:</h3><br>Bovinos: 5 mL vía IM o SC, (revacunar a los 21-30 días en primovacunación y después cada 6 meses) Ovinos y caprinos: 2 mL vía IM o SC.<h3>Composición y especies:</h3><br>Cada dosis de 5 mL contiene: Clostridium chauvoei 8 µl Clostridium septicum ≥ 100 DLM Clostridium haemolyticum 0.4 UH Clostridium sordellii ≥ 500 DLM Clostridium novyi tipo B ≥ 500 DLM Clostridium haemolyticum ≥ 109 UFC Clostridium perfringens tipo D ≥ 200 L+ Clostridium perfringens tipo B ≥ 200 L+ Clostridium perfringens tipo C 200 L+ Clostridium perfringens tipo A ≥ 20 L+ Clostridium tetani ≥ 300000 DLM Vehículo c.s.p. 5 mL Bovinos, Ovinos, Caprinos.<h3>Laboratorio:</h3><br>Presentación: Frasco de 250 mL (50 dosis) y 50 mL (20 dosis).' },
    { name: 'NEONATAL FORTE ST', imageSrc: 'img/biologicos/NEONATAL.png', descripProdu: '<h3>Indicaciones:</h3><br>Con IBR y BVD en DOBLE EMULSIÓN Vacuna utilizada para la Prevención del Síndrome Diarreico Neonatal de los Bovinos producidos por: Rotavirus, Coronavirus, IBR, BVD, Escherichia Coli, Salmonela y Clostridium Perfringens tipo C.<h3>Dosis y Administración:</h3><br>Vía subcutánea. Exclusivamente en la tabla del cuello. BOVINOS: 5 mL VACAS y NOVILLAS GESTANTES: como primovacunación administrar 2 dosis con un intervalo de 20 días. La segunda dosis realizarla 4-5 semanas antes del parto. Revacunar anualmente 4-5 semanas antes de la fecha prevista del parto.<h3>Composición y especies:</h3><br>Agentes, Suspensión Vírica y Bacteriana Inactivada – Enfermedades que Producen: Rotavirus Bovino G 6 (≥ 2,0 x 107 DICT50%/mL) – Diarrea Rotavirus Bovino G 10 (≥ 1,0 x 106 DICT50%/mL) – Diarrea Coronavirus Bovino (≥ 3,0 x 106 DICT50%/mL) – Diarrea Rinotraqueitis Infecciosa Bovina tipo 1 (IBR) ≥ 1 x 107 DICT50%/mL – Infertilidad / Abortos / Respiratorio Rinotraqueitis Infecciosa Bovina tipo 5 (IBR) ≥ 1 x 107 DICT50%/mL – Encefalitis Diarrea Viral Bovina tipo 1 (BVD) ≥ 1,0 x 105 DICT50% – Infertidad/ Abortos / Defectos Congénitos Diarrea Viral Bovina tipo 2 (BVD) ≥ 1,0 x 105 DICT50% – Infertidad/ Abortos / Defectos Congénitos Escherichia Coli J5 (≥1–5×108 UFC/mL) – Diarrea / Septicemia Escherichia Coli K99 F17 serotipos 08 y 09 ≥ 1 – 5x 108 UFC/mL – Diarrea Salmonela Dublin ≥ 1 – 5 x 108 UFC/mL – Diarrea / Septicemia Salmonella Thyphimurium (≥1–5×108 UFC/mL) – Diarrea / Septicemia C. perfringens tipo C ≥ 10 U.I. – Enteritis Hemorrágica / Struck<h3>Laboratorio:</h3><br>Presentación: 50 mL – 10 dosis / 100 mL – 20 dosis y 250 mL – 50 dosis.' },
    { name: 'TRIPLE HA', imageSrc: 'img/biologicos/TRIPLE.png', descripProdu: '<h3>Indicaciones:</h3><br>La vacuna Triple HA está indicada para la inmunización activa de bovinos y ovinos sanos contra: carbón sintomático, edema maligno o gangrena gaseosa y pasteurelosis bovina.<h3>Dosis y Administración:</h3><br>Aplicar exclusivamente a bovinos y ovinos sanos, 5 mL por vía subcutánea (S.C), en la tabla del cuello, en la región pre o pos escapular (delante o detrás de la “paleta”) o en la fosa isquiorrectal (FIR). Se recomienda vacunar animales desde los (3) tres meses de edad. Aplicar refuerzo a las 2 semanas después. Revacunación anual.<h3>Composición y especies:</h3><br>Es una suspensión en hidróxido de aluminio, de 2 microorganismos inactivados (bacterinas) de Pasteurella multocida y Clostridium chauvoei; así como un toxoide inactivado de Clostridium septicum. Bovinos y Ovinos.<h3>Laboratorio:</h3><br>Presentación: Frascos por 20 y 50 dosis.' },
    { name: 'COMBIBAC R8', imageSrc: 'img/biologicos/COMBIBAC.png', descripProdu: '<h3>Indicaciones:</h3><br>Bacterina toxoide para la inmunización activa de Bovinos, Ovinos, Caprinos y Porcinos, en buen estado de salud contra: Carbón Sintomático, Gangrena Gaseosa o Edema Maligno, Riñón pulposo o Enterotoxemia grupo D causada por Clostridium perfringens tipo D. Fiebre de embarque o Pasteurelosis Neumónica causada por Mannheimia haemolytica y Pasteurella multocida, Enterotoxemia causada por C. perfrigens tipos A, B, C y D; Neumonía, Artritis, Pericarditis y Mionecrosis causada por C. sordelli, en Bovinos Hepatitis infecciosa Necrosante causada por C. novyi B en Ovinos.<h3>Dosis y Administración:</h3><br>Vacunar por vía subcutánea: 5 mL en Bovinos; 2 mL en Ovinos, Caprinos y Porcinos. Primovacunación: Entre los 3 y 4 meses de edad. Segunda vacunación: A los 15 a 21 días y anualmente para mantener los niveles de protección. En zonas endémicas vacunar cada seis meses.<h3>Composición y especies:</h3><br>Clostridium chauvoei Clostridium septicum Clostridium novyi Clostridium perfringens C Clostridium perfringens D Clostridium sordelli Pasteurella multocida Mannheimia (Pasteurella) haemolytica. Bovinos, Ovinos.<h3>Laboratorio:</h3>' }
];





// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});

