// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'DESLOGEST', imageSrc: 'img/hormonales/DESLOGEST.png', descripProdu: '<h3>Indicaciones:</h3><br>Inducción de la ovulación dentro de las 48 hs, durante el estro en yeguas con ciclos normales cuyos folículos ováricos tengan un diámetro superior a 30 mm.<h3>Dosis y Administración:</h3><br>Vía intramuscular, en la tabla del cuello. 1 ml por animal.<h3>Composición y especies:</h3><br>Cada 1 ml contiene: Acetato de deslorelina 1,8 mg Agentes de formulación c.s.p. Equinos.<h3>Laboratorio:</h3><br>Presentación: Caja con 5 ampollas de 1 ml de contenido neto cada una.' },
    { name: 'FORCECARB', imageSrc: 'img/hormonales/forcecarb.png', descripProdu: '<h3>Indicaciones:</h3><br>Vacas: Retención placentaria, regulación del parto. Tratamiento y prevención de mastitis y metritis. Cerdas: Agalactia, síndrome MMA, regulación del parto. Tratamiento y prevención de mastitis y metritis. Sincronización del parto luego de aplicación de prostaglandinas.<h3>Dosis y Administración:</h3><br>Vía intramuscular o endovenosa muy lenta. Vacas: 0,3–0,4 ml cada 10 kg de peso vivo o 10 ml por vaca de 400 a 500 kg de peso vivo. Cerdas: 0,12 ml cada 10 kg de peso vivo o 0,2 ml por cerda de 150 a 170 kg de peso vivo.<h3>Composición y especies:</h3><br>Cada ml contiene: Carbetocina 0,05 mg Agentes de formulación c.s.p. Bovinos y Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos con 10 ml de contenido neto.' },
    { name: 'PROSTAL', imageSrc: 'img/hormonales/PROSTAL.png', descripProdu: '<h3>Indicaciones:</h3><br>Sincronización del celo. Inducción al parto o al aborto. Tratamiento de desórdenes funcionales del ciclo estral, de los ovarios (quistes foliculares o luteales) y patologías uterinas post parto (piometras, endometritis).<h3>Dosis y Administración:</h3><br>Vía intramuscular. Bovinos: 2 ml. Equinos: 1 ml. Porcinos: 1 ml.<h3>Composición y especies:</h3><br>Cada 100 ml contiene: D (+) Cloprostenol 0,0075 g Agentes de formulación c.s. Bovinos, Equinos y Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frascos con 20 y 50 ml de contenido neto. Caja con 24 frascos de 2 ml de contenido neto.' },
    { name: 'ANABOL ®', imageSrc: 'img/hormonales/ANABOL.jpg', descripProdu: '<h3>Indicaciones:</h3><br>Anabólico inyectable estimulante del crecimiento, indicado para incrementar la ganancia de peso, favorece la mejor absorción de nutrientes e interviene en la recuperación de animales convalecientes.<h3>Dosis y Administración:</h3><br>Vía intramuscular. Grandes animales: 1 ml por cada 90 kg de peso vivo. Pequeños animales: 0,2 ml por cada 5 kg de peso vivo.<h3>Composición y especies:</h3><br>Laboratorio:' },
    { name: 'GROSS ® NANDROLONA+AD3E', imageSrc: 'img/hormonales/GROSS.png', descripProdu: '<h3>Indicaciones:</h3><br>Actúa como promotor de engorde y desarrollo. Eleva el índice de conversión del alimento en carne por aumento en la asimilación de nitrógeno. Está además indicado en procesos de convalecencia, recuperación de cirugías, animales caídos, crecimiento retrasado, resolución de fracturas, caquexia, distrofia muscular, anemia, osteoporosis, y procesos en los que se considere necesario estimular el apetito y el metabolismo general.<h3>Dosis y Administración:</h3><br>Vía Subcutánea únicamente. Bovinos: 1 ml por cada 50 kg de peso vivo. Ovinos y Porcinos: 1 ml por cada 33 kg de peso vivo.<h3>Composición y especies:</h3><br>Laboratorio:' },
    { name: 'CELOVEC®', imageSrc: 'img/hormonales/CELOVEC.png', descripProdu: '<h3>Indicaciones:</h3><br>En Hembras bovinas, porcinas y ovina, para la sincronización del celo desórdenes funcionales del ciclo estral, patologías uterinas post parto (piometras, endometritis).<h3>Dosis y Administración:</h3><br>Intramuscular. Bovinos: 2 ml por animal (0,150 mg totales). Porcinos: 1 ml por animal (0,075 mg totales). Ovinos: 0,5 ml por animal (0,0375 mg totales). En todos los casos se aplica en dosis única. Para la sincronización de celo se puede utilizar alguno de los siguientes esquemas. En caso de aplicar el esquema de sincronización ciega a tiempo fijo, se aplica Cloprostenol a todos los animales con un intervalo de 11 días entre las aplicaciones y se inseminan todos los individuos entre 72 y 96 horas después de la segunda inyección. Otra alternativa es detectar celo e inseminar después de la primera aplicación; aquellos animales que no manifiesten celo recibirán una segunda aplicación a los 11 días del primer tratamiento y se inseminarán luego de la manifestación del celo.<h3>Composición y especies:</h3><br>Cada 1 ml de la solución inyectable contiene: D- Cloprostenol (equivalente a D – Cloprostenol sódico 0,079 mg) 0,075mg Excipientes: c.s.p 1 ml Bovinos, Porcinos y Ovinos.<h3>Laboratorio:</h3><br>Presentación: Frascos ampolla multidosis por 20 y 50 ml.' },
    { name: 'ESTRAVEC®', imageSrc: 'img/hormonales/ESTRAVEC.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos como coadyuvante para el tratamiento de retención placentaria, piometra, inducción y sincronización de celo. Categoría etaria: Hembras bovinas en etapa reproductiva.<h3>Dosis y Administración:</h3><br>Intramuscular. Se debe administrar 1 a 2,5 mg, equivalente a 1 a 2,5 ml totales según indicación y criterio profesional.<h3>Composición y especies:</h3><br>Cada 100 ml de la solución inyectable contiene: Benzoato de Estradiol 0,1 g Excipientes c.s.p. 100 ml Bovinos.<h3>Laboratorio:</h3><br>Presentación: Caja plegadiza que contiene frasco de vidrio por 100 ml.' },
    { name: 'OXITOCINA SINTÉTICA', imageSrc: 'img/hormonales/OXITOCINA.png', descripProdu: '<h3>Indicaciones:</h3><br>Solución inyectable oxitócico indicado en bovinos, equinos y porcinos utilizado en la estimulación de las contracciones uterinas y el descenso de la leche.<h3>Dosis y Administración:</h3><br>Bovinos: Aumento de contracciones uterinas: 30 UI – vía intramuscular Descenso de la leche: 10-20 UI totales vía intramuscular Equinos: Aumento de las contracciones uterinas: 20 UI vía intramuscular Descenso de la leche: 10-15 UI – vía intramuscular Porcinos: Aumento de las contracciones uterinas: 10 UI vía intramuscular Descenso de la leche: 20-50 UI vía intramuscular<h3>Composición y especies:</h3><br>Oxitocina sintética. Bovinos, Equinos y Porcinos.<h3>Laboratorio:</h3><br>Presentación: Frasco por 10 ml.' },
    { name: 'GONAVEC®', imageSrc: 'img/hormonales/GONAVEC.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos y equinos, para la inducción de la ovulación y tanto en caso de desórdenes ováricos (por ejemplo, quistes) así como programas de mejoramiento de los índices de concepción en las especies indicadas.<h3>Dosis y Administración:</h3><br>Intramuscular profunda, subcutánea o intravenosa. En equinos preferiblemente la vía intravenosa. Vacas: 0,01 a 0,02 mg totales (2,5 – 5 ml totales). Yeguas: 0,04 mg totales (10,0 ml totales). Intervalos entre dosis y duración del tratamiento: el intervalo entre dosis y duración del tratamiento es variable dependiente de la patología a tratar, respuesta clínica o programa de inducción de la ovulación.<h3>Composición y especies:</h3><br>Cada ml de solución inyectable contiene: Buserelina acetato 0,0042 mg (Equivalente a 0,0040mg) Excipientes 1 ml Bovinos y equinos.<h3>Laboratorio:</h3><br>Presentación: Caja plegadiza que contiene frasco de vidrio por 50 ml.' },
    { name: 'GESTAVEC® 25', imageSrc: 'img/hormonales/GESTAVEC.jpg', descripProdu: '<h3>Indicaciones:</h3><br>Hormona luteínica en solución inyectable indicado en bovinos, equinos, porcinos y ovinos para mantener la preñez en casos de amenaza de aborto por insuficiencia en la producción de progesterona.<h3>Dosis y Administración:</h3><br>Bovinos y equinos: Aplicar 2 a 4 ml vía intramuscular profunda Ovinos y porcinos: Aplicar 0,6 a 1 ml vía intramuscular profunda<h3>Composición y especies:</h3><br>Cada ml de solución inyectable contiene: Progesterona 25mg Excipientes 1 ml. Bovinos, Equinos, Ovinos y Porcinos.<h3>Laboratorio:</h3>' }
];




// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});

