// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'CORTIFEN 200.25® | DEXABUTAZON 200.25', imageSrc: 'img/analgesicos/cortifen.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de las afecciones del aparato locomotor de tipo primario y coadyuvante a la antibioterapia en el tratamiento de artritis infecciones. Apropiado en los procesos inflamatorios comunes a osteopatías, adenopatías, neuropatías, mastitis, combatiendo en todos ellos el proceso congestivo y los síntomas dolorosos que los acompañan.<h3>Dosis y Administración:</h3><br>Aplicar vía intramuscular profunda o intravenosa. Equinos: 30 mL el 1º día; 20 mL el 2º día, y posteriormente 10 mL al día, durante 4 - 6 días. Caninos: 1 mL/5 kg. p.v. al día, durante 5 días.<h3>DOSIS TERAPÉUTICA:</h3><br>Equinos: 2,2 mg/kpv, cada 12 horas, o 4,4 mg/kpv, cada 24 horas. Perros: 10 – 15 mg/kpv, cada 12 horas.<h3>Composición y especies:</h3><br>Fenilbutazona 200.00 mg Dexametasona fosfato sódico 0.33 mg Excipientes c.s.p. 1 mL Caninos y Equinos.<h3>Laboratorio</h3> Agrovet Market ' },
    { name: 'TOLFÉN L.A. 8%® | TOLFEMAX A.P. 8%', imageSrc: 'img/analgesicos/tolfe.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de mastitis bovina aguda (el ácido tolfenámico es el único AINE aprobado para tratar las mastitis con una sola inyección), enfermedades respiratorias bacterianas agudas, síndrome mastitis-metritis-agalactia, siempre asociado a una terapia antibiótica. Además, es efectivo en cualquier patología que curse con fiebre, inflamación y/o dolor (terapia antiinflamatoria, antitóxica, analgésica y/o antipirética).<h3>Dosis y Administración:</h3><br>1 mL/40 kg de p.v. vía intramuscular o intravenosa lenta. La dosis será efectiva por 48 horas. En casos de infecciones muy agudas: vía intravenosa, se deberá aplicar una dosis única de 1 mL/20 kg o un tratamiento por 2 días consecutivos a la dosis de 1 mL/40 kg.<h3>DOSIS TERAPÉUTICA:</h3><br>4 mg/kg p.v.<h3>Composición y especies:</h3><br>Ácido tolfenámico 80 mg Excipientes c.s.p. 1 Ml Bovinos, Equinos, Porcinos, Caprinos y Ovinos. <h3>Laboratorio</h3> Agrovet Market' },
    { name: 'DIBROSAL', imageSrc: 'img/analgesicos/DIBROSAL.jpg', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado para el tratamiento de afecciones respiratoria que cursan con producción de moco con alta densidad y fiebre, fluidifica y favorece la expulsión del moco y controla la fiebre.<h3>Dosis y Administración:</h3><br>Vía Oral. 1 kg. Por 1000 litros de agua de bebida. Preparar una pre solución de 1 kg. De Dibrosal en 10 litros de agua. Tratamiento a criterio del Médico Veterinario.<h3>Composición y especies:</h3><br>Aves, Caprinos, Ovinos, Porcinos.<h3>Laboratorio:</h3><br>ALDOR. Laboratorio de sanidad veterinaria' },
    { name: 'OVERXICAM', imageSrc: 'img/analgesicos/overxicam.png', descripProdu: '<h3>Indicaciones:</h3><br><h3>Bovinos:</h3> Tratamiento de infecciones respiratorias agudas, diarreas, mastitis, edema de ubre e inflamaciones podales. <h3>Porcinos:</h3> Trastornos no infecciosos del aparato locomotor, síntomas de cojeras e inflamación, septicemia, toxemia puer-peral. <h3>Equinos:</h3> Trastornos musculoesqueléticos agudos y crónicos.<h3>Dosis y Administración:</h3><br>Bovinos: Vía subcutánea o endovenosa. Porcinos: Vía intramuscular. Equinos: Vía endovenosa. Bovinos: 2,5 ml cada 100 k.p.v. Porcinos: 2 ml cada 100 k.p.v. Equinos: 3 ml cada 100 k.p.v.<h3>DOSIS TERAPÉUTICA:</h3><br>Equinos: 0,6 mg /kpv. Bovinos: 0,5 mg /kpv. Porcinos: 0,4 mg /kpv.<h3>Composición y especies:</h3><br>Cada 100 ml contiene: Meloxicam 2 g Agentes de formulación c.s.p. Bovinos, Porcinos y Equinos.<h3>Laboratorio:</h3><br>OVER. Veterinary Medicine' },
    { name: 'DICOGÁN®', imageSrc: 'img/analgesicos/dicogan.jpg', descripProdu: '<h3>Indicaciones:</h3><br>Solución inyectable con efecto antiinflamatorio, analgésico, antipirético indicado en bovinos, equinos, porcinos, ovinos y caprinos en casos agudos por traumatismo músculo esquelético, como artritis, osteoartritis, bursitis, tendinitis, tendosinovitis. En tratamiento de procesos de dolor visceral y fiebre como cólico y traumatismo de órganos internos. Tratamiento de dolor postquirúrgico.<h3>Dosis y Administración:</h3><br>Aplicar en todas las especies indicadas 1ml/50 kg de peso vivo vía intramuscular, subcutánea o intravenosa.<h3>DOSIS TERAPÉUTICA:</h3><br>2,3 mg de diclofenaco/kg p.v.) durante 1-3 días por vía intramuscular.<h3>Composición y especies:</h3><br>Diclofenaco sódico. Todas las especies.<h3>Laboratorio:</h3><br>VECOL' },
    { name: 'KENOGÁN®', imageSrc: 'img/analgesicos/kenogan.jpg', descripProdu: '<h3>Indicaciones:</h3><br>Solución inyectable con efecto antiinflamatorio, analgésico, antipirético en alteraciones no infecciosas de los sistemas osteoarticular y músculo esquelético. En bovinos y porcinos como coadyuvante en el tratamiento de mastitis bacteriana aguda, junto con la terapia antibiótica necesaria. En porcinos como antipirético. En equinos para aliviar el dolor visceral asociado con cólico. En caninos y gatos para aliviar el dolor y la inflamación en procesos posquirúrgicos o traumáticos.<h3>Dosis y Administración:</h3><br>Bovinos y porcinos: 3 mg de Ketoprofeno/kg de peso vivo, es decir 3 ml de producto/100 kg de peso durante 1 a 3 días consecutivos para bovinos vía intramuscular o intravenosa y una única administración para porcinos por vía intramuscular. Equinos: 2 mg de Ketoprofeno/kg de peso vivo, equivalente a 1 ml de producto/45 kg de peso vía intravenosa durante 1 a 3 días consecutivos. Caninos y gatos: aplicar 0,5 ml / 25 kg de peso vivo durante 1 a 3 días consecutivos. En caninos: aplicar por vía intramuscular (I.M) o intravenosa (I.V). En gatos: aplicar por vía subcutánea.<h3>DOSIS TERAPÉUTICA:</h3><br>Bovinos y porcinos: 3 mg/kg de peso vivo. Equinos: 2 mg/kg de peso vivo. Caninos y gatos: aplicar 0,5 ml / 25 kg de peso vivo durante 1 a 3 días consecutivos.<h3>Composición y especies:</h3><br>Ketoprofeno. Bovinos, Equinos, Porcinos, Caninos y Felinos.<h3>Laboratorio:</h3><br>VECOL' },
    { name: 'DEXAMETASONA FM®', imageSrc: 'img/analgesicos/dexametasona.png', descripProdu: '<h3>Indicaciones:</h3><br>Antinflamatorio, Analgésico, Antirreumático. Indicado en alergias, artritis, hipoglicemias, inflamaciones, traumatismo y estrés en Bovinos, Equinos, Porcinos, Ovinos, Caprinos y pequeños animales.<h3>Dosis y Administración:</h3><br>Vía intravenosa, intramuscular o subcutánea. Bovinos, Bubalinos, Ovinos y Caprinos: 2.5 - 10 ml. Equino: 1,25 - 2,5 ml. Porcinos: 0,5 - 1 ml. Caninos: 0,12 - 0,5 ml. Felinos: 0,06 - 0,25 ml. Dosis recomendada como antiinflamatorio. La dosis puede aumentarse o repetirse según criterio del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>0,02-0,2 mg/kg p.v., en dosis única<h3>Composición y especies:</h3><br>Cada 1 cm³ contienen: Dexametasona Base 2 mg Excipientes c.s.p. 1 ml<h3>Laboratorio:</h3><br>Farmacéutica mundial' },
    { name: 'DIPIRONA 50%®', imageSrc: 'img/analgesicos/dipirona.png', descripProdu: '<h3>Indicaciones:</h3><br>Antiinflamatorio no esteroideo, con acción analgésica, antipirética, antiespasmódica y antiinflamatoria. Indicado para el tratamiento y la prevención de todos aquellos procesos agudos y crónicos que cursen con inflamación, dolor, fiebre, espasmos, cólicos, procesos osteoarticulares y musculoesqueleticos como artritis, artrosis, osteoartritis, etc, enfermedad articular degenerativa síndrome ciático, para la prevención de inflamaciones postoperatorias, shock endotóxico.<h3>Dosis y Administración:</h3><br>Parental, por vía intravenosa lenta preferentemente; en caso de ser administrada por vía intramuscular debe ser profunda. Equinos: 20 a 50mg/kg de peso. Bovinos: 20 a 40 mg/kg de peso. Porcinos: 15 a 50 mg/kg de peso.<h3>DOSIS TERAPÉUTICA:</h3><br>Equinos: 20 a 50mg/kg de peso. Bovinos: 20 a 40 mg/kg de peso. Porcinos: 15 a 50 mg/kg de peso.<h3>Composición y especies:</h3><br>Cada 100 cm³ contienen: Dipirona Sódica 50 g Excipientes c.s.p. 100 ml<h3>Laboratorio:</h3><br>Farmacéutica mundial' },
    { name: 'FURODEX®', imageSrc: 'img/analgesicos/furodex.png', descripProdu: '<h3>Indicaciones:</h3><br>Edemas de ubre y estructuras anexas, edema o inflamación de prepucio, ascitis, hidrotórax. Edemas generalizados (anasarca), pulmonares y bronquiales de origen parasitario o traumático.<h3>Dosis y Administración:</h3><br>Bovinos y Equinos: 1-2 mL por 20 Kg de peso, según la intensidad del edema, repetir la mitad de la dosis al 2do y 3er día. Porcinos: 10-20 mL de acuerdo a su peso, después mantener 10 mL por 2 días. Caninos: 1-2 mL inicialmente de acuerdo al tamaño, luego 1 ml al 2do y 3er día.<h3>DOSIS TERAPÉUTICA:</h3><br>4-6 mg/kg IV, IM, o SC, según sea necesario para terapias agudas. Perros: 2-4 mg/kg, PO, una a tres veces al día. Gatos: 1-2 mg/kg, PO, una o dos veces al día. Animales grandes: 0,5-1 mg/kg/día, IV o IM.<h3>Composición y especies:</h3><br>Furosemida 5% Dexametasona 0,05 %<h3>Laboratorio:</h3><br>VALMORCA,C.A' },
    { name: 'FYNACOL®', imageSrc: 'img/analgesicos/fynacol.png', descripProdu: '<h3>Indicaciones:</h3><br>En procesos inflamatorios y dolorosos tales como neumonías, artritis, tendinitis, espondilitis, fracturas, orquitis, metritis, mastitis y cólicos; en cualquier proceso doloroso asociado a traumatismo o alteraciones neurológicas y en caso de reacciones inflamatorias producidas por shock séptico.<h3>Dosis y Administración:</h3><br>Vía IM, SC, IV. Bovinos: 2 mL / 45 Kg de peso y Equinos y caninos: 1 mL / 45 Kg de peso (hasta un máximo de 4 días).<h3>DOSIS TERAPÉUTICA:</h3><br>1.1-2.2mg/1kpv.<h3>Composición y especies:</h3><br>Flunixin meglumine 5%<h3>Laboratorio:</h3><br>VALMORCA,C.A' },
    // { name: 'ERITROGEN®', imageSrc: 'img/anestesicos/eritrogen.png', descripProdu: '<h3>Indicaciones:</h3><br>En caso de anemias microciticas e hipocrómicas o producidas por hemorragias, para la recuperación después de parasitosis producida por: Tripanosoma, Anaplasma y Piroplasma, como reconstituyente después de infecciones bacterianas, virales y en animales después de la temporada de servicio. Estimulante de la producción de carne y leche. Para tratar estados depresivos.<h3>Dosis y Administración:</h3><br>Vía de administración, inyección: Intramuscular, Intravenosa lenta y subcutánea. Bovinos y Equinos: 4 mL por cada 100 Kg. Porcinos, Ovinos y Caprinos: 1 mL por cada 25 Kg. En Bovinos, Ovinos, Caprinos y Porcinos se recomienda aplicar de 3 a 5 inyecciones a intervalo de 48 a 72 horas. Para la preparación de animales de concurso 1 a 2 inyecciones por cada semana durante 1 mes previo al evento.<h3>DOSIS TERAPÉUTICA:</h3><br>1-4ml/25-100kpv.<h3>Composición y especies:</h3><br>Hierro, cobre, cobalto, magnesio, vitamina B, aminoácidos, A.T.P y Dinitrilo succínico.<h3>Laboratorio:</h3><br>VALMORCA,C.A' }
];


// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});
