// productrecomendamos.js
const productListRecomendamos = document.getElementById('product-listrecomendamos');

// Ejemplo de productos recomendados
const productsRecomendados = [
    { name: 'ANTRIFORMINT FM ®', imageSrc: 'img/product/ANTRIFORMINT.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de anaplasmosis y babesia en bovinos, búfalos, equinos, ovinos y caprinos. Antibiótico de amplio espectro. Polvo para reconstituir.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Bovinos, Búfalos, Ovinos y Caprinos: 1,5 ml por 20 kg de peso vivo. Equinos: dividir dosis y aplicar con intervalos de 2 horas para evitar síntomas de cólico.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3><br>Cada 100 cm³ contienen: Oxitetraciclina HCL 200 mg Antipirina 150 mg Diminazeno 70 mg Excipientes c.s.p. 100 ml' },
    { name: 'ANTRIBAM 4G ®', imageSrc: 'img/product/atriban.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos, búfalos, ovinos y caprinos para la prevención, tratamiento y control de la tripanosomiasis.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Polvo para reconstituir. Agítese antes de usar. <h4>Dosis preventiva:</h4> 1 ml por cada 80 kg de peso vivo. <h4>Dosis curativa:</h4> En zonas de baja incidencia 1 ml por cada 40 kg de peso vivo. En zonas de mediana o alta incidencia 2 ml por cada 40 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>0,5 mg<h3>Composición y especies:</h3><br>Cada 100 cm³ contienen: Cloruro de isometamidium 4 g Diluyente estéril 200 ml' },
    { name: 'ASCEND ®', imageSrc: 'img/product/ascend.png', descripProdu: '<h3>Indicaciones:</h3><br>Está indicado para la prevención y tratamiento de la piroplasmosis, anaplasmosis, ehrlichiosis, hepatozoonosis y citauxzoonosis.<h3>Dosis y Administración:</h3><br>Vía subcutánea o intramuscular. Bovinos, Ovinos y Caprinos: 1 - 2,5 ml por cada 100 kg de peso vivo. Equinos: 2 ml por cada 100 kg de peso vivo. Caninos: 0,5 ml por cada 10 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>1-5 mg<h3>Composición y especies:</h3><br>Cada 100 cm³ contienen: Imidocarb Dipropionato 12 g Excipientes c.s.p. 100 ml' },
    { name: 'ENROFLOXACINA 10% ®', imageSrc: 'img/product/enrofloxasina.png', descripProdu: '<h3>Indicaciones:</h3><br>Para tratamiento de procesos infecciosos del aparato respiratorio, digestivo y genitourinario. Infecciones virales e infecciones de la piel causadas por gérmenes grampositivos, gramnegativos y micoplasma en Bovinos, Ovinos, Caprinos, Porcinos, Felinos y Caninos.<h3>Dosis y Administración:</h3><br>Vía subcutánea, intramuscular o intravenosa. (en el anca). Las ovejas y las cabras se inyectan en los músculos del muslo. <h4>Bovinos, Ovinos, Caprinos y Porcinos: </h4> 1 ml por cada 40 kg de peso vivo. En casos graves, aplicar 1ml por cada 20 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3><br>Cada 1 cm³ contienen: Enrofloxacina 100 mg Excipientes c.s.p. 1 ml' },
    { name: 'FLUXIPEN ®', imageSrc: 'img/product/fluxipen.png', descripProdu: '<h3>Indicaciones:</h3><br>Antibiótico de rápido efecto y prolongada acción en infecciones causadas por gérmenes sensibles a la penicilina. Suspensión inyectable estéril.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Dosis General: 1 ml por 20 kg de peso vivo. Aplicar 3 ml por cada 50 - 100 de peso vivo. Tratamiento: de 1 a 3 días consecutivos. Después de reconstruir es estable por 30 días en refrigeración.<h3>DOSIS TERAPÉUTICA:</h3><br>11.000 - 22.000 UI<h3>Composición y especies:</h3><br>Cada 100 cm³ contienen: Oxitetraciclina HCL 200 mg Antipirina 150 mg Diminazeno 70 mg Excipientes c.s.p. 100 ml' },
    { name: 'RESANIQ ®', imageSrc: 'img/product/RESANIQ.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos, ovinos, caprinos y porcinos en el tratamiento preventivo y curativo de infecciones respiratorias (pasteurelosis, neumonía, bronconeumonía, pleuroneumonía), infecciones urogenitales (cistitis, nefritis, metritis, síndrome MMA de las cerdas), infecciones cutáneas y tejidos blandos (pododermatitis abscesos) e infecciones postparto.<h3>Dosis y Administración:</h3><br>Vía intramuscular o subcutánea. Porcinos, Ovinos, Bovinos y Caprinos: 1 ml por cada 10 kg de peso vivo. Repetir la dosis a las 48 horas.<h3>DOSIS TERAPÉUTICA:</h3><br>10 mg<h3>Composición y especies:</h3><br>Cada 100 cm³ contienen: Amoxicilina 15 g Excipientes C.S.P. 100 ml' }
    

];

// Agregar cada producto al DOM
productsRecomendados.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListRecomendamos.appendChild(productElement);
});

