// productnovedades.js
const productListNovedades = document.getElementById('product-listrenovedades');

// Ejemplo de productos novedades (puedes usar los mismos o diferentes)
const productsNovedades = [
    { name: 'B-FOX ®', imageSrc: 'categorias/img/multivitaminico/b-fox.png', descripProdu: '<h3>Indicaciones:</h3><br>Complejo vitamínico, reconstituyente y tónico general. Desarrollado con tecnología doble emulsión. Es una suspensión inyectable que combina diversos elementos hematopoyéticos, estimulantes del crecimiento y del apetito. Destacando en su formulación: las altas concentraciones de vitaminas del complejo B, vitamina A, vitamina D3, vitamina E, aminoácidos y fosfocolamina (fósforo).<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. En bovinos, equinos y búfalos: Adultos 20 cm³. Medianos 10 cm³. Pequeños 5 cm³. Terneros y potrillos: 5 cm³. Ovinos y caprinos: Adultos y medianos 10 cm³. Pequeños 5 cm³. Porcinos: 1-2 cm³. Caninos, felinos y gatos: 1-2 cm³.<h3>DOSIS TERAPÉUTICA:</h3><br>10-20 mg/kg cada 8-12 horas.<h3>Composición y especies:</h3> Cada 100 cm³ contienen Tiamina (B1) 1000 mg Riboflavina (B2) 300 mg Piridoxina (B6) 350 mg Nicotinamida 2000 mg Cianocobalamina (B12) 1000 mg D-Pantenol 400 mg Triptofano 240 mg Histidina 500 mg Fosforilcolamina 5000 mg Vitamina E 500 mg Vitamina A 1000000 UT Vitamina D3 150000 UT Excipientes c.s.p 100 ml' },
    { name: 'COMBETRION GOLD ®', imageSrc: 'categorias/img/multivitaminico/conbe.png', descripProdu: '<h3>Indicaciones:</h3><br> En bovinos, equinos, ovinos, porcinos, caprinos, conejos, caninos, felinos y aves para el tratamiento de trastornos digestivos, nerviosos, de la piel, metabólicos, musculares y anemias. Como estimulante del apetito. Aumenta la producción lechera, la postura y engorde de pollos. En caso de deficiencias de los componentes en formula. <h3>Dosis y Administración:</h3><br>Vía oral. Bovinos, equinos, ovinos, caprinos y porcinos: 20 - 30 ml. Dos veces al día, durante 7 días. Caninos, felinos: 3 ml por litro de agua, durante 7 días. Aves: 10 ml por cada 2 litros de agua, durante 7 días.<h3>DOSIS TERAPÉUTICA:</h3><br>13 mg.<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Nicotinamida 400 mg Tiamina 100 mg Piridoxina 20 mg Riboflavina 30 mg Cloruro de Magnesio 50 mg Cloruro de calcio 120 mg Lisina 1000 mg Triptofano 100 mg Metionina 500 mg Hierro 100 mg Excipientes c.s.p. 100 ml' },
    { name: 'MINERFUN PLUS ®', imageSrc: 'categorias/img/multivitaminico/MINERFUN.png', descripProdu: '<h3>Indicaciones:</h3><br>Suspensión inyectable de vitaminas AD3E, ATP y minerales esenciales, destacando con gran importancia en el área reproductiva de toda especie animal: el selenio (selenito de sodio), hierro (citrato de hierro) y fósforo (fosfocolamina). Reconstituyente indicado para mejorar los procesos reproductivos en vacas de leche y preñez. En hembras, mejora el porcentaje de celo y preñez. Reduce la retención de placenta y la aparición de metritis. En machos, aumenta la libido y la calidad del semen. En todos los casos se aplica en dosis única.<h3>Dosis y Administración:</h3><br>Únicamente inyección intramuscular. Bovinos, búfalos y equinos: 2 ml cada 100 kg de peso vivo. Porcinos, ovinos y caprinos: 1 ml por cada 15 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>Bovinos: Adultos: 500.000-1.000 UI. Terneros: 250.000 UI. Equinos: Adultos: 500.000-1.000.000 UI. Potros: 250.000 UI. Porcinos: 250.000 UI. Ovinos: 250.000 UI. Caprinos: 250.000 UI.<h3>Composición y especies:</h3> Cada 100 cm³ contienen: Vitamina A 3.000.000 UI Vitamina D3 1.000.000 UI Vitamina E 1000 UI Selenio 100 mg Cloruro de Calcio 500 mg Cloruro de Magnesio 800 mg Cloruro de Zinc 100 mg Cloruro de Hierro 200 mg Sulfato de Manganeso 200 mg Sulfato Cúprico 50 mg Cloruro de Sodio 1.000 mg Yoduro de Potasio 42 mg Sulfato Ferroso 600 mg Excipientes c.s.p 100 ml' },
    { name: 'RAKET ®', imageSrc: 'categorias/img/multivitaminico/RAKET.png', descripProdu: '<h3>Indicaciones:</h3><br> Reconstituyente, regulador y estimulador fisiológico del metabolismo, estimulante de la asimilación protéica y tónico general, impulsor regenerativo en insuficiencias y retardo en el crecimiento en Bovinos, Bufalinos, Ovinos, Caprinos y Porcinos. <h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Bovinos, búfalos, ovinos, caprinos y porcinos: 1 ml por cada 100 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>Bovinos: Adultos: 500.000-1.000.000 UI. Terneros: 250.000 UI. Equinos: Adultos: 500.000-1.000.000 UI. Potros: 250.000 UI. Porcinos: 250.000 UI. Ovinos: 250.000 UI. Caprinos: 250.000 UI.<h3>Composición y especies:</h3> Cada 100 cm³ contienen Vitamina A 500000 UI Vitamina E 3000 UI Ácido Hipofosforoso 0,033 g Nicotinamida (B3) 9,24 g Tiamina (B1) 5,61 g Piridoxina (B6) 1,815 g Riboflavina (B2) 2,475 g Vitamina B12 0,0396 g Lisina 2,00 g Histidina 1,50 g Triptofano 0,99 g Metionina 1,98 g D-Pantenol 0,363 g Citrato De Hierro 0,1155 g Excipientes c.s.p 100 ml' },
    { name: 'MODIFICADOR ORGÁNICO ®', imageSrc: 'categorias/img/multivitaminico/MODIFICADOR.png', descripProdu: '<h3>Indicaciones:</h3><br>En bovinos, ovinos, caprinos, porcinos: como reconstituyente estimulante del metabolismo, como auxiliar en deficiencias nutricionales, para restablecer vacas después del parto, preparar novillas gestantes, recuperar reproductores durante el descanso. En hembras, mejora el porcentaje de celo y preñez. Reduce la retención de placenta y la aparición de metritis. En machos, aumenta la libido y la calidad del semen.<h3>Dosis y Administración:</h3><br>Vía subcutánea e intramuscular. Bovinos, ovinos, caprinos y porcinos: 1 ml por cada 50 kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>Bovinos: Terneros: 125.000-250.000 UI. Adultos: 250.000-500.000 UI. Equinos: Potros: 125.000 UI. Adultos: 250.000-500.000 UI. Porcinos: 125.000 UI. Ovinos: 125.000 UI. Caprinos: 125.000 UI.<h3>Composición y especies: </h3> Cada 100 cm³ contienen Vitamina D3 2000000 UI Vitamina E 100 UI Cianocobalamina 5000 mg Cloruro de Magnesio 210 mg Cloruro de sodio 42 mg Fenol 0,5 ml Cloruro de Zinc 10 mg Sulfato de Cobre 2 mg Yoduro de Potasio 15 mg Cloruro Cálcico 1500 mg Fosfato Monosódico 200 mg Glicina 420 mg Histidina 210 mg Leucina 210 mg Lisina 1000 mg Metionina 210 mg Triptofano 50 mg Sodio Monoglutamato 420 mg Valina 200 mg Arginina 200 mg Ácido oleico (Omega 9) 750 mg Ácido Fólico 5 mg Excipientes c.s.p 100 ml' },
    
];


// Agregar cada producto al DOM
productsNovedades.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListNovedades.appendChild(productElement);
});






// const productsNovedades = [
//     { name: 'SONENIX 150®', imageSrc: 'img/product-novedades/sonenix.png', descripProdu: '<h3>Indicaciones:</h3><br>Para Bovinos, Porcinos, Caprinos y Ovinos en el tratamiento de mastitis infecciosa y pododermatitis en ganado bovino, tratamiento en infecciones respiratorias, urogenitales, gastrointestinales, de piel y tejidos blandos.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Bovinos: 1 ml por cada 15 a 20 kg de peso cada 24 horas entre 3 a 5 días Porcinos, Ovinos y Caprinos: 1 ml por cada 15 kg de peso entre 3 a 5 días. Cada 12 a 24 horas.<h3>DOSIS TERAPÉUTICA:</h3><br>15 mg' },
//     { name: 'ENOMETROL®', imageSrc: 'img/product-novedades/Enometrol.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de infecciones respiratorias, genito-urinarias provocadas por bacterias gramnegativas y grampositivas. Infecciones de la cavidad oral y afecciones cutáneas.<h3>Dosis y Administración:</h3><br>Vía oral. 0,2 ml por cada kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>La dosis máxima que se debe administrar es de 50 - 65 mg/kg por día en cualquier especie.' },
//     { name: 'AMOXIGEN', imageSrc: 'img/product-novedades/amoxigen.png', descripProdu: '<h3>Indicaciones:</h3><br>Bovinos: Infecciones causadas por bacterias sensibles a la combinación de Amoxicilina y Gentamicina, como las presentes en neumonías, enteritis bacteriana, mastitis, metritis y abscesos cutáneos.<h3>Dosis y Administración:</h3><br>Intramuscular Profunda. 1 ml por 10 kg de peso, durante 3 días. bajo supervisión del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>10 mg<h3>Composición y especies:</h3><br>Contiene por ml: Amoxicilina Trihidrato 150 mg. Gentamicina base 40 mg Excipientes c.s.p. 1 ml. Bovinos, Porcinos.' },
//     { name: 'OXITETRACICLINA AL 5%', imageSrc: 'img/product-novedades/OXITETRACICLINA.png', descripProdu: '<h3>Indicaciones:</h3><br><h4>Bovinos:</h4> Para tratar Anaplasmosis, Lesiones Pódales, Leptospirosis, Metritis, sensibles a Oxitetraciclina. <h4>Porcinos:</h4> Para tratar el Síndrome Mastitis Metritis Agalactia (MMA), Neumonía, Lesiones Pódales, sensibles a Oxitetraciclina. <h4>Ovinos:</h4> Para tratar Pasteurelosis, Clamidiasis, Neumonía, Lesiones Pódales, sensibles a Oxitetraciclina. <h4>Aves:</h4> para tratar Coriza, Colera, Enfermedad Crónica Respiratoria (ECR), sensibles a Oxitetraciclina.<h3>Dosis y Administración:</h3><br>Intramuscular profunda. En general 1 cm3 por cada 5 kg de peso vivo. Aves: 0,5 cm3 a 1 cm3 por ave adulta (2,5 a 5kgs) repetir cada 24 horas o a criterio del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3><br>Oxitetraciclina 50 mg Bovinos, Porcinos, Caprinos, Ovinos, Equinos, Aves.' },
//     { name: 'FLORFENICOL L.A.', imageSrc: 'img/product-novedades/FLORFENICOL.png', descripProdu: '<h3>Indicaciones:</h3><br>Antibiótico de amplio espectro que actúa contra bacterias gram positivas y gram negativas del ganado bovino, ovino, caprino, porcino y aves, como: Pasteurellas, Haemophylus somnus, Klebsiella sp., Escherichia coli, Moraxella sp., Salmonella sp., Bacteroides sp., Fusobacterium sp., Corynebacterium pyogenes, Clostridium sp., Streptococcus, causantes de infecciones como neumonías, pododermatitis, metritis, enteritis y en general, procesos susceptibles a bacterias sensibles al Florfenicol.<h3>Dosis y Administración:</h3><br>Subcutánea o intramuscular preferiblemente en la tabla del cuello. Bovinos, Ovinos y Caprinos: 1 ml por cada 20 Kg de peso (20 mg/kg), una segunda aplicación a las 48 horas 1 ml por cada 10 Kg de peso (40 mg/kg). Porcinos: 1 ml por cada 25 a 30 Kg de peso (15 mg/Kg), una segunda aplicación a las 48 horas. Aves: 0,15 ml por cada 2 Kg de peso. Esta dosis puede ser modificada por el Médico Veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>4-11 mg. IM/IV 2-4 mg.<h3>Composición y especies:</h3><br>Cada 100 ml contiene: Florfenicol 400 mg Vehículo c.s.p. 1 ml Bovinos, Porcinos, Caprinos, Ovinos, Aves.' },
//     { name: 'SULFACET', imageSrc: 'img/product-novedades/SULFACET.png', descripProdu: '<h3>Indicaciones:</h3><br>Sirve para combatir infecciones generales, agudas o crónicas, causadas por bacterias gram negativas o positivas, sensibles a la formulación en bovinos, equinos, ovinos, caprinos y porcinos. Esta indicado en Neumonías, Bronquitis Infecciosas, Difterias de los terneros, Enteritis Bacilar, Septicemia Hemorrágica, Metritis Séptica y Retención Placentaria; Mastitis Aguda, Poliartritis, Colibacilosis, Flemones y Abscesos, en infecciones secundarias de la Diarrea Blanca del ternero y como auxiliar en el tratamiento de la “Chinela» y en cualquier otra infección donde este indicado el tratamiento sulfamídico.<h3>Dosis y Administración:</h3><br>Intravenosa ó intramuscular. En Bovinos, Equinos, Ovinos, Caprinos y Porcinos, como dosis inicial o de ataque, de 25 a 40 ml por cada 100 Kg de peso según criterio del facultativo. Después como dosis de mantenimiento, la mitad de la dosis inicial, diariamente por un término de 5 días. Retiro en carne 3 días y retiro en leche 7 días.<h3>DOSIS TERAPÉUTICA:</h3><br>25 mg<h3>Composición y especies:</h3><br>Cada 100 ml. contiene: Sulfadiazina Sódica 8.5 g Sulfadimidina Sódica 8 g Sulfamerazina Sódica 8.5 g Dextrosa Anhidra 15 g Excipientes c.s.p. 100 ml Bovinos, Equinos, Ovinos, Caprinos y Porcinos.' }
// ];