// productnovedades.js
const productListNovedades = document.getElementById('product-listrenovedades');

// Ejemplo de productos novedades (puedes usar los mismos o diferentes)
const productsNovedades = [
    { name: 'SONENIX 150®', imageSrc: 'img/product-novedades/sonenix.png', descripProdu: '<h3>Indicaciones:</h3><br>Para Bovinos, Porcinos, Caprinos y Ovinos en el tratamiento de mastitis infecciosa y pododermatitis en ganado bovino, tratamiento en infecciones respiratorias, urogenitales, gastrointestinales, de piel y tejidos blandos.<h3>Dosis y Administración:</h3><br>Vía intramuscular profunda. Bovinos: 1 ml por cada 15 a 20 kg de peso cada 24 horas entre 3 a 5 días Porcinos, Ovinos y Caprinos: 1 ml por cada 15 kg de peso entre 3 a 5 días. Cada 12 a 24 horas.<h3>DOSIS TERAPÉUTICA:</h3><br>15 mg' },
    { name: 'ENOMETROL®', imageSrc: 'img/product-novedades/Enometrol.png', descripProdu: '<h3>Indicaciones:</h3><br>Para el tratamiento de infecciones respiratorias, genito-urinarias provocadas por bacterias gramnegativas y grampositivas. Infecciones de la cavidad oral y afecciones cutáneas.<h3>Dosis y Administración:</h3><br>Vía oral. 0,2 ml por cada kg de peso vivo.<h3>DOSIS TERAPÉUTICA:</h3><br>La dosis máxima que se debe administrar es de 50 - 65 mg/kg por día en cualquier especie.' },
    { name: 'AMOXIGEN', imageSrc: 'img/product-novedades/amoxigen.png', descripProdu: '<h3>Indicaciones:</h3><br>Bovinos: Infecciones causadas por bacterias sensibles a la combinación de Amoxicilina y Gentamicina, como las presentes en neumonías, enteritis bacteriana, mastitis, metritis y abscesos cutáneos.<h3>Dosis y Administración:</h3><br>Intramuscular Profunda. 1 ml por 10 kg de peso, durante 3 días. bajo supervisión del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>10 mg<h3>Composición y especies:</h3><br>Contiene por ml: Amoxicilina Trihidrato 150 mg. Gentamicina base 40 mg Excipientes c.s.p. 1 ml. Bovinos, Porcinos.' },
    { name: 'OXITETRACICLINA AL 5%', imageSrc: 'img/product-novedades/OXITETRACICLINA.png', descripProdu: '<h3>Indicaciones:</h3><br><h4>Bovinos:</h4> Para tratar Anaplasmosis, Lesiones Pódales, Leptospirosis, Metritis, sensibles a Oxitetraciclina. <h4>Porcinos:</h4> Para tratar el Síndrome Mastitis Metritis Agalactia (MMA), Neumonía, Lesiones Pódales, sensibles a Oxitetraciclina. <h4>Ovinos:</h4> Para tratar Pasteurelosis, Clamidiasis, Neumonía, Lesiones Pódales, sensibles a Oxitetraciclina. <h4>Aves:</h4> para tratar Coriza, Colera, Enfermedad Crónica Respiratoria (ECR), sensibles a Oxitetraciclina.<h3>Dosis y Administración:</h3><br>Intramuscular profunda. En general 1 cm3 por cada 5 kg de peso vivo. Aves: 0,5 cm3 a 1 cm3 por ave adulta (2,5 a 5kgs) repetir cada 24 horas o a criterio del médico veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>8-10 mg<h3>Composición y especies:</h3><br>Oxitetraciclina 50 mg Bovinos, Porcinos, Caprinos, Ovinos, Equinos, Aves.' },
    { name: 'FLORFENICOL L.A.', imageSrc: 'img/product-novedades/FLORFENICOL.png', descripProdu: '<h3>Indicaciones:</h3><br>Antibiótico de amplio espectro que actúa contra bacterias gram positivas y gram negativas del ganado bovino, ovino, caprino, porcino y aves, como: Pasteurellas, Haemophylus somnus, Klebsiella sp., Escherichia coli, Moraxella sp., Salmonella sp., Bacteroides sp., Fusobacterium sp., Corynebacterium pyogenes, Clostridium sp., Streptococcus, causantes de infecciones como neumonías, pododermatitis, metritis, enteritis y en general, procesos susceptibles a bacterias sensibles al Florfenicol.<h3>Dosis y Administración:</h3><br>Subcutánea o intramuscular preferiblemente en la tabla del cuello. Bovinos, Ovinos y Caprinos: 1 ml por cada 20 Kg de peso (20 mg/kg), una segunda aplicación a las 48 horas 1 ml por cada 10 Kg de peso (40 mg/kg). Porcinos: 1 ml por cada 25 a 30 Kg de peso (15 mg/Kg), una segunda aplicación a las 48 horas. Aves: 0,15 ml por cada 2 Kg de peso. Esta dosis puede ser modificada por el Médico Veterinario.<h3>DOSIS TERAPÉUTICA:</h3><br>4-11 mg. IM/IV 2-4 mg.<h3>Composición y especies:</h3><br>Cada 100 ml contiene: Florfenicol 400 mg Vehículo c.s.p. 1 ml Bovinos, Porcinos, Caprinos, Ovinos, Aves.' },
    { name: 'SULFACET', imageSrc: 'img/product-novedades/SULFACET.png', descripProdu: '<h3>Indicaciones:</h3><br>Sirve para combatir infecciones generales, agudas o crónicas, causadas por bacterias gram negativas o positivas, sensibles a la formulación en bovinos, equinos, ovinos, caprinos y porcinos. Esta indicado en Neumonías, Bronquitis Infecciosas, Difterias de los terneros, Enteritis Bacilar, Septicemia Hemorrágica, Metritis Séptica y Retención Placentaria; Mastitis Aguda, Poliartritis, Colibacilosis, Flemones y Abscesos, en infecciones secundarias de la Diarrea Blanca del ternero y como auxiliar en el tratamiento de la “Chinela» y en cualquier otra infección donde este indicado el tratamiento sulfamídico.<h3>Dosis y Administración:</h3><br>Intravenosa ó intramuscular. En Bovinos, Equinos, Ovinos, Caprinos y Porcinos, como dosis inicial o de ataque, de 25 a 40 ml por cada 100 Kg de peso según criterio del facultativo. Después como dosis de mantenimiento, la mitad de la dosis inicial, diariamente por un término de 5 días. Retiro en carne 3 días y retiro en leche 7 días.<h3>DOSIS TERAPÉUTICA:</h3><br>25 mg<h3>Composición y especies:</h3><br>Cada 100 ml. contiene: Sulfadiazina Sódica 8.5 g Sulfadimidina Sódica 8 g Sulfamerazina Sódica 8.5 g Dextrosa Anhidra 15 g Excipientes c.s.p. 100 ml Bovinos, Equinos, Ovinos, Caprinos y Porcinos.' }
];


// Agregar cada producto al DOM
productsNovedades.forEach(product => {
    const productElement = createProduct(product.name, product.imageSrc, product.descripProdu);
    productListNovedades.appendChild(productElement);
});

